package se.info24.ismOperationsPojo;
// Generated Feb 8, 2012 2:22:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DriversLogItemHistory generated by hbm2java
 */
public class DriversLogItemHistory  implements java.io.Serializable {


     private String driversLogItemId;
     private String deviceId;
     private String deviceGroupId;
     private String deviceName;
     private String driverUserId;
     private String driverName;
     private Date startTime;
     private Date stopTime;
     private int totalTime;
     private int startOdometer;
     private int stopOdometer;
     private BigDecimal totalDistance;
     private BigDecimal startLatitude;
     private BigDecimal startLongitude;
     private BigDecimal startAltitude;
     private Integer startHeading;
     private String startAddress;
     private String startCity;
     private BigDecimal stopLatitude;
     private BigDecimal stopLongitude;
     private BigDecimal stopAltitude;
     private Integer stopHeading;
     private String stopAddress;
     private String stopCity;
     private String journeyTypeId;
     private String journeyPurpose;
     private String journeyAccount;
     private String journeyNote;
     private String journeyWorkOrder;
     private String journeyWorkOrderId;
     private Integer isDeleted;
     private Integer isReadyForExport;
     private Integer isExported;
     private Date exportedDate;
     private BigDecimal averageSpeed;
     private BigDecimal maxSpeed;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public DriversLogItemHistory() {
    }

	
    public DriversLogItemHistory(String driversLogItemId, String deviceId, String driverUserId, Date startTime, Date stopTime, int totalTime, int startOdometer, int stopOdometer, BigDecimal totalDistance, BigDecimal startLatitude, BigDecimal startLongitude, String startAddress, BigDecimal stopLatitude, BigDecimal stopLongitude, String stopAddress) {
        this.driversLogItemId = driversLogItemId;
        this.deviceId = deviceId;
        this.driverUserId = driverUserId;
        this.startTime = startTime;
        this.stopTime = stopTime;
        this.totalTime = totalTime;
        this.startOdometer = startOdometer;
        this.stopOdometer = stopOdometer;
        this.totalDistance = totalDistance;
        this.startLatitude = startLatitude;
        this.startLongitude = startLongitude;
        this.startAddress = startAddress;
        this.stopLatitude = stopLatitude;
        this.stopLongitude = stopLongitude;
        this.stopAddress = stopAddress;
    }
    public DriversLogItemHistory(String driversLogItemId, String deviceId, String deviceGroupId, String deviceName, String driverUserId, String driverName, Date startTime, Date stopTime, int totalTime, int startOdometer, int stopOdometer, BigDecimal totalDistance, BigDecimal startLatitude, BigDecimal startLongitude, BigDecimal startAltitude, Integer startHeading, String startAddress, String startCity, BigDecimal stopLatitude, BigDecimal stopLongitude, BigDecimal stopAltitude, Integer stopHeading, String stopAddress, String stopCity, String journeyTypeId, String journeyPurpose, String journeyAccount, String journeyNote, String journeyWorkOrder, String journeyWorkOrderId, Integer isDeleted, Integer isReadyForExport, Integer isExported, Date exportedDate, BigDecimal averageSpeed, BigDecimal maxSpeed, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.driversLogItemId = driversLogItemId;
       this.deviceId = deviceId;
       this.deviceGroupId = deviceGroupId;
       this.deviceName = deviceName;
       this.driverUserId = driverUserId;
       this.driverName = driverName;
       this.startTime = startTime;
       this.stopTime = stopTime;
       this.totalTime = totalTime;
       this.startOdometer = startOdometer;
       this.stopOdometer = stopOdometer;
       this.totalDistance = totalDistance;
       this.startLatitude = startLatitude;
       this.startLongitude = startLongitude;
       this.startAltitude = startAltitude;
       this.startHeading = startHeading;
       this.startAddress = startAddress;
       this.startCity = startCity;
       this.stopLatitude = stopLatitude;
       this.stopLongitude = stopLongitude;
       this.stopAltitude = stopAltitude;
       this.stopHeading = stopHeading;
       this.stopAddress = stopAddress;
       this.stopCity = stopCity;
       this.journeyTypeId = journeyTypeId;
       this.journeyPurpose = journeyPurpose;
       this.journeyAccount = journeyAccount;
       this.journeyNote = journeyNote;
       this.journeyWorkOrder = journeyWorkOrder;
       this.journeyWorkOrderId = journeyWorkOrderId;
       this.isDeleted = isDeleted;
       this.isReadyForExport = isReadyForExport;
       this.isExported = isExported;
       this.exportedDate = exportedDate;
       this.averageSpeed = averageSpeed;
       this.maxSpeed = maxSpeed;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public String getDriversLogItemId() {
        return this.driversLogItemId;
    }
    
    public void setDriversLogItemId(String driversLogItemId) {
        this.driversLogItemId = driversLogItemId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public String getDeviceGroupId() {
        return this.deviceGroupId;
    }
    
    public void setDeviceGroupId(String deviceGroupId) {
        this.deviceGroupId = deviceGroupId;
    }
    public String getDeviceName() {
        return this.deviceName;
    }
    
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }
    public String getDriverUserId() {
        return this.driverUserId;
    }
    
    public void setDriverUserId(String driverUserId) {
        this.driverUserId = driverUserId;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getStopTime() {
        return this.stopTime;
    }
    
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }
    public int getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(int totalTime) {
        this.totalTime = totalTime;
    }
    public int getStartOdometer() {
        return this.startOdometer;
    }
    
    public void setStartOdometer(int startOdometer) {
        this.startOdometer = startOdometer;
    }
    public int getStopOdometer() {
        return this.stopOdometer;
    }
    
    public void setStopOdometer(int stopOdometer) {
        this.stopOdometer = stopOdometer;
    }
    public BigDecimal getTotalDistance() {
        return this.totalDistance;
    }
    
    public void setTotalDistance(BigDecimal totalDistance) {
        this.totalDistance = totalDistance;
    }
    public BigDecimal getStartLatitude() {
        return this.startLatitude;
    }
    
    public void setStartLatitude(BigDecimal startLatitude) {
        this.startLatitude = startLatitude;
    }
    public BigDecimal getStartLongitude() {
        return this.startLongitude;
    }
    
    public void setStartLongitude(BigDecimal startLongitude) {
        this.startLongitude = startLongitude;
    }
    public BigDecimal getStartAltitude() {
        return this.startAltitude;
    }
    
    public void setStartAltitude(BigDecimal startAltitude) {
        this.startAltitude = startAltitude;
    }
    public Integer getStartHeading() {
        return this.startHeading;
    }
    
    public void setStartHeading(Integer startHeading) {
        this.startHeading = startHeading;
    }
    public String getStartAddress() {
        return this.startAddress;
    }
    
    public void setStartAddress(String startAddress) {
        this.startAddress = startAddress;
    }
    public String getStartCity() {
        return this.startCity;
    }
    
    public void setStartCity(String startCity) {
        this.startCity = startCity;
    }
    public BigDecimal getStopLatitude() {
        return this.stopLatitude;
    }
    
    public void setStopLatitude(BigDecimal stopLatitude) {
        this.stopLatitude = stopLatitude;
    }
    public BigDecimal getStopLongitude() {
        return this.stopLongitude;
    }
    
    public void setStopLongitude(BigDecimal stopLongitude) {
        this.stopLongitude = stopLongitude;
    }
    public BigDecimal getStopAltitude() {
        return this.stopAltitude;
    }
    
    public void setStopAltitude(BigDecimal stopAltitude) {
        this.stopAltitude = stopAltitude;
    }
    public Integer getStopHeading() {
        return this.stopHeading;
    }
    
    public void setStopHeading(Integer stopHeading) {
        this.stopHeading = stopHeading;
    }
    public String getStopAddress() {
        return this.stopAddress;
    }
    
    public void setStopAddress(String stopAddress) {
        this.stopAddress = stopAddress;
    }
    public String getStopCity() {
        return this.stopCity;
    }
    
    public void setStopCity(String stopCity) {
        this.stopCity = stopCity;
    }
    public String getJourneyTypeId() {
        return this.journeyTypeId;
    }
    
    public void setJourneyTypeId(String journeyTypeId) {
        this.journeyTypeId = journeyTypeId;
    }
    public String getJourneyPurpose() {
        return this.journeyPurpose;
    }
    
    public void setJourneyPurpose(String journeyPurpose) {
        this.journeyPurpose = journeyPurpose;
    }
    public String getJourneyAccount() {
        return this.journeyAccount;
    }
    
    public void setJourneyAccount(String journeyAccount) {
        this.journeyAccount = journeyAccount;
    }
    public String getJourneyNote() {
        return this.journeyNote;
    }
    
    public void setJourneyNote(String journeyNote) {
        this.journeyNote = journeyNote;
    }
    public String getJourneyWorkOrder() {
        return this.journeyWorkOrder;
    }
    
    public void setJourneyWorkOrder(String journeyWorkOrder) {
        this.journeyWorkOrder = journeyWorkOrder;
    }
    public String getJourneyWorkOrderId() {
        return this.journeyWorkOrderId;
    }
    
    public void setJourneyWorkOrderId(String journeyWorkOrderId) {
        this.journeyWorkOrderId = journeyWorkOrderId;
    }
    public Integer getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Integer getIsReadyForExport() {
        return this.isReadyForExport;
    }
    
    public void setIsReadyForExport(Integer isReadyForExport) {
        this.isReadyForExport = isReadyForExport;
    }
    public Integer getIsExported() {
        return this.isExported;
    }
    
    public void setIsExported(Integer isExported) {
        this.isExported = isExported;
    }
    public Date getExportedDate() {
        return this.exportedDate;
    }
    
    public void setExportedDate(Date exportedDate) {
        this.exportedDate = exportedDate;
    }
    public BigDecimal getAverageSpeed() {
        return this.averageSpeed;
    }
    
    public void setAverageSpeed(BigDecimal averageSpeed) {
        this.averageSpeed = averageSpeed;
    }
    public BigDecimal getMaxSpeed() {
        return this.maxSpeed;
    }
    
    public void setMaxSpeed(BigDecimal maxSpeed) {
        this.maxSpeed = maxSpeed;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


