//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.10 at 02:58:24 PM IST 
//


package se.info24.supportcasejaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.info24.supportcasejaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MsgTimeStamp_QNAME = new QName("", "MsgTimeStamp");
    private final static QName _ResponseText_QNAME = new QName("", "ResponseText");
    private final static QName _UpdatedDate_QNAME = new QName("", "UpdatedDate");
    private final static QName _MsgID_QNAME = new QName("", "MsgID");
    private final static QName _SupportOrganizationID_QNAME = new QName("", "SupportOrganizationID");
    private final static QName _ActiveToDate_QNAME = new QName("", "ActiveToDate");
    private final static QName _SupportCaseTypeID_QNAME = new QName("", "SupportCaseTypeID");
    private final static QName _SupportCaseStatusID_QNAME = new QName("", "SupportCaseStatusID");
    private final static QName _CreatedDate_QNAME = new QName("", "CreatedDate");
    private final static QName _ResponseCode_QNAME = new QName("", "ResponseCode");
    private final static QName _SupportCasePriorityID_QNAME = new QName("", "SupportCasePriorityID");
    private final static QName _ActiveFromDate_QNAME = new QName("", "ActiveFromDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.info24.supportcasejaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupID }
     * 
     */
    public GroupID createGroupID() {
        return new GroupID();
    }

    /**
     * Create an instance of {@link SupportOrganizationsVisibleToGroups }
     * 
     */
    public SupportOrganizationsVisibleToGroups createSupportOrganizationsVisibleToGroups() {
        return new SupportOrganizationsVisibleToGroups();
    }

    /**
     * Create an instance of {@link SupportCase }
     * 
     */
    public SupportCase createSupportCase() {
        return new SupportCase();
    }

    /**
     * Create an instance of {@link CostCenters }
     * 
     */
    public CostCenters createCostCenters() {
        return new CostCenters();
    }

    /**
     * Create an instance of {@link MsgStatus }
     * 
     */
    public MsgStatus createMsgStatus() {
        return new MsgStatus();
    }

    /**
     * Create an instance of {@link SupportPriorityTranslations }
     * 
     */
    public SupportPriorityTranslations createSupportPriorityTranslations() {
        return new SupportPriorityTranslations();
    }

    /**
     * Create an instance of {@link SupportOrganizations }
     * 
     */
    public SupportOrganizations createSupportOrganizations() {
        return new SupportOrganizations();
    }

    /**
     * Create an instance of {@link SupportCaseSubjectTemplates }
     * 
     */
    public SupportCaseSubjectTemplates createSupportCaseSubjectTemplates() {
        return new SupportCaseSubjectTemplates();
    }

    /**
     * Create an instance of {@link SupportCaseImpacts }
     * 
     */
    public SupportCaseImpacts createSupportCaseImpacts() {
        return new SupportCaseImpacts();
    }

    /**
     * Create an instance of {@link SupportCaseStatuses }
     * 
     */
    public SupportCaseStatuses createSupportCaseStatuses() {
        return new SupportCaseStatuses();
    }

    /**
     * Create an instance of {@link SupportImpactTranslations }
     * 
     */
    public SupportImpactTranslations createSupportImpactTranslations() {
        return new SupportImpactTranslations();
    }

    /**
     * Create an instance of {@link SupportCases }
     * 
     */
    public SupportCases createSupportCases() {
        return new SupportCases();
    }

    /**
     * Create an instance of {@link SupportStatusTranslations }
     * 
     */
    public SupportStatusTranslations createSupportStatusTranslations() {
        return new SupportStatusTranslations();
    }

    /**
     * Create an instance of {@link SupportTypeTranslations }
     * 
     */
    public SupportTypeTranslations createSupportTypeTranslations() {
        return new SupportTypeTranslations();
    }

    /**
     * Create an instance of {@link SupportCaseResolutionTemplates }
     * 
     */
    public SupportCaseResolutionTemplates createSupportCaseResolutionTemplates() {
        return new SupportCaseResolutionTemplates();
    }

    /**
     * Create an instance of {@link SupportCasePriorities }
     * 
     */
    public SupportCasePriorities createSupportCasePriorities() {
        return new SupportCasePriorities();
    }

    /**
     * Create an instance of {@link SupportCaseTypes }
     * 
     */
    public SupportCaseTypes createSupportCaseTypes() {
        return new SupportCaseTypes();
    }

    /**
     * Create an instance of {@link TingcoSupportCase }
     * 
     */
    public TingcoSupportCase createTingcoSupportCase() {
        return new TingcoSupportCase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgTimeStamp")
    public JAXBElement<XMLGregorianCalendar> createMsgTimeStamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MsgTimeStamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseText")
    public JAXBElement<String> createResponseText(String value) {
        return new JAXBElement<String>(_ResponseText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdatedDate")
    public JAXBElement<XMLGregorianCalendar> createUpdatedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UpdatedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgID")
    public JAXBElement<String> createMsgID(String value) {
        return new JAXBElement<String>(_MsgID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupportOrganizationID")
    public JAXBElement<String> createSupportOrganizationID(String value) {
        return new JAXBElement<String>(_SupportOrganizationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActiveToDate")
    public JAXBElement<String> createActiveToDate(String value) {
        return new JAXBElement<String>(_ActiveToDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupportCaseTypeID")
    public JAXBElement<String> createSupportCaseTypeID(String value) {
        return new JAXBElement<String>(_SupportCaseTypeID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupportCaseStatusID")
    public JAXBElement<String> createSupportCaseStatusID(String value) {
        return new JAXBElement<String>(_SupportCaseStatusID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreatedDate")
    public JAXBElement<XMLGregorianCalendar> createCreatedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreatedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseCode")
    public JAXBElement<Integer> createResponseCode(Integer value) {
        return new JAXBElement<Integer>(_ResponseCode_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupportCasePriorityID")
    public JAXBElement<String> createSupportCasePriorityID(String value) {
        return new JAXBElement<String>(_SupportCasePriorityID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActiveFromDate")
    public JAXBElement<String> createActiveFromDate(String value) {
        return new JAXBElement<String>(_ActiveFromDate_QNAME, String.class, null, value);
    }

}
