//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.12 at 01:04:12 PM IST 
//


package se.info24.devicejaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceDataItemID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataItemName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProductVariantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductVariantName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastUpdatedDate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ScaledMinValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ScaledMaxValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="FreeLevel" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="FilledLevel" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="FillLevelPercent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}Scaling" minOccurs="0"/>
 *         &lt;element ref="{}WarningLevels" minOccurs="0"/>
 *         &lt;element ref="{}AlarmLevels" minOccurs="0"/>
 *         &lt;element ref="{}ProductLink" minOccurs="0"/>
 *         &lt;element ref="{}DataItemTranslationsPerDevice" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SeqNo" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "DeviceDataItemScaling")
public class DeviceDataItemScaling {

    @XmlElementRefs({
        @XmlElementRef(name = "CountryId", type = JAXBElement.class),
        @XmlElementRef(name = "LastUpdatedDate", type = JAXBElement.class),
        @XmlElementRef(name = "DeviceName", type = JAXBElement.class),
        @XmlElementRef(name = "ProductVariantID", type = JAXBElement.class),
        @XmlElementRef(name = "ScaledMinValue", type = JAXBElement.class),
        @XmlElementRef(name = "FillLevelPercent", type = JAXBElement.class),
        @XmlElementRef(name = "ProductVariantName", type = JAXBElement.class),
        @XmlElementRef(name = "DeviceID", type = JAXBElement.class),
        @XmlElementRef(name = "DataItemTranslationsPerDevice", type = DataItemTranslationsPerDevice.class),
        @XmlElementRef(name = "FilledLevel", type = JAXBElement.class),
        @XmlElementRef(name = "ProductLink", type = ProductLink.class),
        @XmlElementRef(name = "WarningLevels", type = WarningLevels.class),
        @XmlElementRef(name = "Status", type = JAXBElement.class),
        @XmlElementRef(name = "ScaledMaxValue", type = JAXBElement.class),
        @XmlElementRef(name = "AlarmLevels", type = AlarmLevels.class),
        @XmlElementRef(name = "DataItemName", type = JAXBElement.class),
        @XmlElementRef(name = "Scaling", type = Scaling.class),
        @XmlElementRef(name = "DeviceDataItemID", type = JAXBElement.class),
        @XmlElementRef(name = "FreeLevel", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "SeqNo", required = true)
    protected int seqNo;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * {@link DataItemTranslationsPerDevice }
     * {@link WarningLevels }
     * {@link ProductLink }
     * {@link AlarmLevels }
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Scaling }
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     */
    public int getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     */
    public void setSeqNo(int value) {
        this.seqNo = value;
    }

}
