//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 11:00:27 AM IST 
//


package se.info24.devicejaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserRoleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PermissionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}LastUpdatedByUserID"/>
 *         &lt;element ref="{}CreatedDate"/>
 *         &lt;element ref="{}UpdatedDate"/>
 *         &lt;element ref="{}DeviceTypeID" minOccurs="0"/>
 *         &lt;element ref="{}DeviceTypeCommandTranslations" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PermissionTranslations" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userRoleID",
    "permissionID",
    "objectID",
    "lastUpdatedByUserID",
    "createdDate",
    "updatedDate",
    "deviceTypeID",
    "deviceTypeCommandTranslations",
    "permissionTranslations"
})
@XmlRootElement(name = "UserRoleObjectPermissions2")
public class UserRoleObjectPermissions2 {

    @XmlElement(name = "UserRoleID", required = true)
    protected String userRoleID;
    @XmlElement(name = "PermissionID", required = true)
    protected String permissionID;
    @XmlElement(name = "ObjectID", required = true)
    protected String objectID;
    @XmlElement(name = "LastUpdatedByUserID", required = true)
    protected LastUpdatedByUserID lastUpdatedByUserID;
    @XmlElement(name = "CreatedDate", required = true)
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "UpdatedDate", required = true)
    protected XMLGregorianCalendar updatedDate;
    @XmlElement(name = "DeviceTypeID")
    protected DeviceTypeID deviceTypeID;
    @XmlElement(name = "DeviceTypeCommandTranslations")
    protected List<DeviceTypeCommandTranslations> deviceTypeCommandTranslations;
    @XmlElement(name = "PermissionTranslations")
    protected List<PermissionTranslations> permissionTranslations;

    /**
     * Gets the value of the userRoleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRoleID() {
        return userRoleID;
    }

    /**
     * Sets the value of the userRoleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRoleID(String value) {
        this.userRoleID = value;
    }

    /**
     * Gets the value of the permissionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermissionID() {
        return permissionID;
    }

    /**
     * Sets the value of the permissionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermissionID(String value) {
        this.permissionID = value;
    }

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectID(String value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the lastUpdatedByUserID property.
     * 
     * @return
     *     possible object is
     *     {@link LastUpdatedByUserID }
     *     
     */
    public LastUpdatedByUserID getLastUpdatedByUserID() {
        return lastUpdatedByUserID;
    }

    /**
     * Sets the value of the lastUpdatedByUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastUpdatedByUserID }
     *     
     */
    public void setLastUpdatedByUserID(LastUpdatedByUserID value) {
        this.lastUpdatedByUserID = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the deviceTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceTypeID }
     *     
     */
    public DeviceTypeID getDeviceTypeID() {
        return deviceTypeID;
    }

    /**
     * Sets the value of the deviceTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceTypeID }
     *     
     */
    public void setDeviceTypeID(DeviceTypeID value) {
        this.deviceTypeID = value;
    }

    /**
     * Gets the value of the deviceTypeCommandTranslations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceTypeCommandTranslations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceTypeCommandTranslations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceTypeCommandTranslations }
     * 
     * 
     */
    public List<DeviceTypeCommandTranslations> getDeviceTypeCommandTranslations() {
        if (deviceTypeCommandTranslations == null) {
            deviceTypeCommandTranslations = new ArrayList<DeviceTypeCommandTranslations>();
        }
        return this.deviceTypeCommandTranslations;
    }

    /**
     * Gets the value of the permissionTranslations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the permissionTranslations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPermissionTranslations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PermissionTranslations }
     * 
     * 
     */
    public List<PermissionTranslations> getPermissionTranslations() {
        if (permissionTranslations == null) {
            permissionTranslations = new ArrayList<PermissionTranslations>();
        }
        return this.permissionTranslations;
    }

}
