//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.09 at 11:00:36 AM IST 
//


package se.info24.networkjaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetworkSubscriptionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupID" type="{}GroupID"/>
 *         &lt;element name="AgreementID" type="{}AgreementID"/>
 *         &lt;element name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetworkID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetworkType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetworkSubscriptionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetworkSubscriptionDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionEnabled" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="InvoiceSubscription" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}CreatedDate" minOccurs="0"/>
 *         &lt;element name="CreatedDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}UpdatedDate" minOccurs="0"/>
 *         &lt;element name="SubscriptionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionNumberTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPV4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPV6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillingAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ICCID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="APN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostCenterID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostCenterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostCenterNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NetworkSubscriptionsStatusID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}NetworkSubscriptionStatus" maxOccurs="unbounded"/>
 *         &lt;element ref="{}ActiveToDate"/>
 *         &lt;element ref="{}ActiveFromDate"/>
 *         &lt;element name="ActiveFromDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActiveToDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Networks" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}NetworkTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}NetworkSubscriptionsPendingDelete" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Costcenters" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SeqNo" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "networkSubscriptionID",
    "groupID",
    "agreementID",
    "deviceID",
    "networkID",
    "networkType",
    "networkSubscriptionName",
    "networkSubscriptionDescription",
    "subscriptionEnabled",
    "invoiceSubscription",
    "userID",
    "createdDate",
    "createdDateTCMV3",
    "updatedDate",
    "subscriptionNumber",
    "subscriptionNumberTypeID",
    "subscriptionPassword",
    "ipv4",
    "ipv6",
    "billingAccount",
    "subscriptionUser",
    "iccid",
    "apn",
    "costCenterID",
    "costCenterName",
    "costCenterNumber",
    "countryID",
    "networkSubscriptionsStatusID",
    "networkSubscriptionStatus",
    "activeToDate",
    "activeFromDate",
    "activeFromDateTCMV3",
    "activeToDateTCMV3",
    "networks",
    "networkTypes",
    "networkSubscriptionsPendingDelete",
    "costcenters"
})
@XmlRootElement(name = "NetworkSubscription")
public class NetworkSubscription {

    @XmlElement(name = "NetworkSubscriptionID", required = true)
    protected String networkSubscriptionID;
    @XmlElement(name = "GroupID", required = true)
    protected GroupID groupID;
    @XmlElement(name = "AgreementID", required = true)
    protected AgreementID agreementID;
    @XmlElement(name = "DeviceID", required = true)
    protected String deviceID;
    @XmlElement(name = "NetworkID", required = true)
    protected String networkID;
    @XmlElement(name = "NetworkType", required = true)
    protected String networkType;
    @XmlElement(name = "NetworkSubscriptionName", required = true)
    protected String networkSubscriptionName;
    @XmlElement(name = "NetworkSubscriptionDescription", required = true)
    protected String networkSubscriptionDescription;
    @XmlElement(name = "SubscriptionEnabled")
    protected int subscriptionEnabled;
    @XmlElement(name = "InvoiceSubscription", required = true)
    protected BigInteger invoiceSubscription;
    @XmlElement(name = "UserID", required = true)
    protected String userID;
    @XmlElement(name = "CreatedDate")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "CreatedDateTCMV3", required = true)
    protected String createdDateTCMV3;
    @XmlElement(name = "UpdatedDate")
    protected XMLGregorianCalendar updatedDate;
    @XmlElement(name = "SubscriptionNumber", required = true)
    protected String subscriptionNumber;
    @XmlElement(name = "SubscriptionNumberTypeID", required = true)
    protected String subscriptionNumberTypeID;
    @XmlElement(name = "SubscriptionPassword", required = true)
    protected String subscriptionPassword;
    @XmlElement(name = "IPV4", required = true)
    protected String ipv4;
    @XmlElement(name = "IPV6", required = true)
    protected String ipv6;
    @XmlElement(name = "BillingAccount", required = true)
    protected String billingAccount;
    @XmlElement(name = "SubscriptionUser", required = true)
    protected String subscriptionUser;
    @XmlElement(name = "ICCID", required = true)
    protected String iccid;
    @XmlElement(name = "APN", required = true)
    protected String apn;
    @XmlElement(name = "CostCenterID", required = true)
    protected String costCenterID;
    @XmlElement(name = "CostCenterName", required = true)
    protected String costCenterName;
    @XmlElement(name = "CostCenterNumber", required = true)
    protected String costCenterNumber;
    @XmlElement(name = "CountryID")
    protected int countryID;
    @XmlElement(name = "NetworkSubscriptionsStatusID", required = true)
    protected String networkSubscriptionsStatusID;
    @XmlElement(name = "NetworkSubscriptionStatus", required = true)
    protected List<NetworkSubscriptionStatus> networkSubscriptionStatus;
    @XmlElement(name = "ActiveToDate", required = true)
    protected String activeToDate;
    @XmlElement(name = "ActiveFromDate", required = true)
    protected String activeFromDate;
    @XmlElement(name = "ActiveFromDateTCMV3", required = true)
    protected String activeFromDateTCMV3;
    @XmlElement(name = "ActiveToDateTCMV3", required = true)
    protected String activeToDateTCMV3;
    @XmlElement(name = "Networks")
    protected List<Networks> networks;
    @XmlElement(name = "NetworkTypes")
    protected List<NetworkTypes> networkTypes;
    @XmlElement(name = "NetworkSubscriptionsPendingDelete")
    protected List<NetworkSubscriptionsPendingDelete> networkSubscriptionsPendingDelete;
    @XmlElement(name = "Costcenters")
    protected List<Costcenters> costcenters;
    @XmlAttribute(name = "SeqNo", required = true)
    protected int seqNo;

    /**
     * Gets the value of the networkSubscriptionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkSubscriptionID() {
        return networkSubscriptionID;
    }

    /**
     * Sets the value of the networkSubscriptionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkSubscriptionID(String value) {
        this.networkSubscriptionID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link GroupID }
     *     
     */
    public GroupID getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupID }
     *     
     */
    public void setGroupID(GroupID value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the agreementID property.
     * 
     * @return
     *     possible object is
     *     {@link AgreementID }
     *     
     */
    public AgreementID getAgreementID() {
        return agreementID;
    }

    /**
     * Sets the value of the agreementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgreementID }
     *     
     */
    public void setAgreementID(AgreementID value) {
        this.agreementID = value;
    }

    /**
     * Gets the value of the deviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the networkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkID() {
        return networkID;
    }

    /**
     * Sets the value of the networkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkID(String value) {
        this.networkID = value;
    }

    /**
     * Gets the value of the networkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkType() {
        return networkType;
    }

    /**
     * Sets the value of the networkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkType(String value) {
        this.networkType = value;
    }

    /**
     * Gets the value of the networkSubscriptionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkSubscriptionName() {
        return networkSubscriptionName;
    }

    /**
     * Sets the value of the networkSubscriptionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkSubscriptionName(String value) {
        this.networkSubscriptionName = value;
    }

    /**
     * Gets the value of the networkSubscriptionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkSubscriptionDescription() {
        return networkSubscriptionDescription;
    }

    /**
     * Sets the value of the networkSubscriptionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkSubscriptionDescription(String value) {
        this.networkSubscriptionDescription = value;
    }

    /**
     * Gets the value of the subscriptionEnabled property.
     * 
     */
    public int getSubscriptionEnabled() {
        return subscriptionEnabled;
    }

    /**
     * Sets the value of the subscriptionEnabled property.
     * 
     */
    public void setSubscriptionEnabled(int value) {
        this.subscriptionEnabled = value;
    }

    /**
     * Gets the value of the invoiceSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvoiceSubscription() {
        return invoiceSubscription;
    }

    /**
     * Sets the value of the invoiceSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvoiceSubscription(BigInteger value) {
        this.invoiceSubscription = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the createdDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDateTCMV3() {
        return createdDateTCMV3;
    }

    /**
     * Sets the value of the createdDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDateTCMV3(String value) {
        this.createdDateTCMV3 = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the subscriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionNumber() {
        return subscriptionNumber;
    }

    /**
     * Sets the value of the subscriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionNumber(String value) {
        this.subscriptionNumber = value;
    }

    /**
     * Gets the value of the subscriptionNumberTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionNumberTypeID() {
        return subscriptionNumberTypeID;
    }

    /**
     * Sets the value of the subscriptionNumberTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionNumberTypeID(String value) {
        this.subscriptionNumberTypeID = value;
    }

    /**
     * Gets the value of the subscriptionPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionPassword() {
        return subscriptionPassword;
    }

    /**
     * Sets the value of the subscriptionPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionPassword(String value) {
        this.subscriptionPassword = value;
    }

    /**
     * Gets the value of the ipv4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPV4() {
        return ipv4;
    }

    /**
     * Sets the value of the ipv4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPV4(String value) {
        this.ipv4 = value;
    }

    /**
     * Gets the value of the ipv6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPV6() {
        return ipv6;
    }

    /**
     * Sets the value of the ipv6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPV6(String value) {
        this.ipv6 = value;
    }

    /**
     * Gets the value of the billingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAccount() {
        return billingAccount;
    }

    /**
     * Sets the value of the billingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAccount(String value) {
        this.billingAccount = value;
    }

    /**
     * Gets the value of the subscriptionUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionUser() {
        return subscriptionUser;
    }

    /**
     * Sets the value of the subscriptionUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionUser(String value) {
        this.subscriptionUser = value;
    }

    /**
     * Gets the value of the iccid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICCID() {
        return iccid;
    }

    /**
     * Sets the value of the iccid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICCID(String value) {
        this.iccid = value;
    }

    /**
     * Gets the value of the apn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPN() {
        return apn;
    }

    /**
     * Sets the value of the apn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPN(String value) {
        this.apn = value;
    }

    /**
     * Gets the value of the costCenterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterID() {
        return costCenterID;
    }

    /**
     * Sets the value of the costCenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterID(String value) {
        this.costCenterID = value;
    }

    /**
     * Gets the value of the costCenterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterName() {
        return costCenterName;
    }

    /**
     * Sets the value of the costCenterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterName(String value) {
        this.costCenterName = value;
    }

    /**
     * Gets the value of the costCenterNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterNumber() {
        return costCenterNumber;
    }

    /**
     * Sets the value of the costCenterNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterNumber(String value) {
        this.costCenterNumber = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     */
    public int getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     */
    public void setCountryID(int value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the networkSubscriptionsStatusID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkSubscriptionsStatusID() {
        return networkSubscriptionsStatusID;
    }

    /**
     * Sets the value of the networkSubscriptionsStatusID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkSubscriptionsStatusID(String value) {
        this.networkSubscriptionsStatusID = value;
    }

    /**
     * Gets the value of the networkSubscriptionStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkSubscriptionStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkSubscriptionStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkSubscriptionStatus }
     * 
     * 
     */
    public List<NetworkSubscriptionStatus> getNetworkSubscriptionStatus() {
        if (networkSubscriptionStatus == null) {
            networkSubscriptionStatus = new ArrayList<NetworkSubscriptionStatus>();
        }
        return this.networkSubscriptionStatus;
    }

    /**
     * Gets the value of the activeToDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveToDate() {
        return activeToDate;
    }

    /**
     * Sets the value of the activeToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveToDate(String value) {
        this.activeToDate = value;
    }

    /**
     * Gets the value of the activeFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFromDate() {
        return activeFromDate;
    }

    /**
     * Sets the value of the activeFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFromDate(String value) {
        this.activeFromDate = value;
    }

    /**
     * Gets the value of the activeFromDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFromDateTCMV3() {
        return activeFromDateTCMV3;
    }

    /**
     * Sets the value of the activeFromDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFromDateTCMV3(String value) {
        this.activeFromDateTCMV3 = value;
    }

    /**
     * Gets the value of the activeToDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveToDateTCMV3() {
        return activeToDateTCMV3;
    }

    /**
     * Sets the value of the activeToDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveToDateTCMV3(String value) {
        this.activeToDateTCMV3 = value;
    }

    /**
     * Gets the value of the networks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Networks }
     * 
     * 
     */
    public List<Networks> getNetworks() {
        if (networks == null) {
            networks = new ArrayList<Networks>();
        }
        return this.networks;
    }

    /**
     * Gets the value of the networkTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkTypes }
     * 
     * 
     */
    public List<NetworkTypes> getNetworkTypes() {
        if (networkTypes == null) {
            networkTypes = new ArrayList<NetworkTypes>();
        }
        return this.networkTypes;
    }

    /**
     * Gets the value of the networkSubscriptionsPendingDelete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkSubscriptionsPendingDelete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkSubscriptionsPendingDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkSubscriptionsPendingDelete }
     * 
     * 
     */
    public List<NetworkSubscriptionsPendingDelete> getNetworkSubscriptionsPendingDelete() {
        if (networkSubscriptionsPendingDelete == null) {
            networkSubscriptionsPendingDelete = new ArrayList<NetworkSubscriptionsPendingDelete>();
        }
        return this.networkSubscriptionsPendingDelete;
    }

    /**
     * Gets the value of the costcenters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costcenters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostcenters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Costcenters }
     * 
     * 
     */
    public List<Costcenters> getCostcenters() {
        if (costcenters == null) {
            costcenters = new ArrayList<Costcenters>();
        }
        return this.costcenters;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     */
    public int getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     */
    public void setSeqNo(int value) {
        this.seqNo = value;
    }

}
