//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.27 at 10:37:55 AM IST 
//


package se.info24.apidocJAXB;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SourceName"/>
 *         &lt;element ref="{}SourceURL"/>
 *         &lt;element ref="{}APIDescription"/>
 *         &lt;element ref="{}APIEncoding"/>
 *         &lt;element ref="{}APIErrorCodes"/>
 *         &lt;element ref="{}Methods"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeZone" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="UTC"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RegionalUnits" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Metric"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MsgVer" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CreateRef" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Info24"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceName",
    "sourceURL",
    "apiDescription",
    "apiEncoding",
    "apiErrorCodes",
    "methods"
})
@XmlRootElement(name = "APIDocMessage")
public class APIDocMessage {

    @XmlElement(name = "SourceName", required = true)
    protected String sourceName;
    @XmlElement(name = "SourceURL", required = true)
    protected String sourceURL;
    @XmlElement(name = "APIDescription", required = true)
    protected APIDescription apiDescription;
    @XmlElement(name = "APIEncoding", required = true)
    protected String apiEncoding;
    @XmlElement(name = "APIErrorCodes", required = true)
    protected APIErrorCodes apiErrorCodes;
    @XmlElement(name = "Methods", required = true)
    protected Methods methods;
    @XmlAttribute(name = "TimeZone", required = true)
    protected String timeZone;
    @XmlAttribute(name = "RegionalUnits", required = true)
    protected String regionalUnits;
    @XmlAttribute(name = "MsgVer", required = true)
    protected BigDecimal msgVer;
    @XmlAttribute(name = "CreateRef", required = true)
    protected String createRef;

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the sourceURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceURL() {
        return sourceURL;
    }

    /**
     * Sets the value of the sourceURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceURL(String value) {
        this.sourceURL = value;
    }

    /**
     * Gets the value of the apiDescription property.
     * 
     * @return
     *     possible object is
     *     {@link APIDescription }
     *     
     */
    public APIDescription getAPIDescription() {
        return apiDescription;
    }

    /**
     * Sets the value of the apiDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link APIDescription }
     *     
     */
    public void setAPIDescription(APIDescription value) {
        this.apiDescription = value;
    }

    /**
     * Gets the value of the apiEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPIEncoding() {
        return apiEncoding;
    }

    /**
     * Sets the value of the apiEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPIEncoding(String value) {
        this.apiEncoding = value;
    }

    /**
     * Gets the value of the apiErrorCodes property.
     * 
     * @return
     *     possible object is
     *     {@link APIErrorCodes }
     *     
     */
    public APIErrorCodes getAPIErrorCodes() {
        return apiErrorCodes;
    }

    /**
     * Sets the value of the apiErrorCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link APIErrorCodes }
     *     
     */
    public void setAPIErrorCodes(APIErrorCodes value) {
        this.apiErrorCodes = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link Methods }
     *     
     */
    public Methods getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Methods }
     *     
     */
    public void setMethods(Methods value) {
        this.methods = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the regionalUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionalUnits() {
        return regionalUnits;
    }

    /**
     * Sets the value of the regionalUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionalUnits(String value) {
        this.regionalUnits = value;
    }

    /**
     * Gets the value of the msgVer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMsgVer() {
        return msgVer;
    }

    /**
     * Sets the value of the msgVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMsgVer(BigDecimal value) {
        this.msgVer = value;
    }

    /**
     * Gets the value of the createRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateRef() {
        return createRef;
    }

    /**
     * Sets the value of the createRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateRef(String value) {
        this.createRef = value;
    }

}
