//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 11:25:29 AM IST 
//


package se.info24.devicejaxbPost;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DeviceTypeID" minOccurs="0"/>
 *         &lt;element ref="{}DeviceTypeAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deviceTypeID",
    "deviceTypeAttribute"
})
@XmlRootElement(name = "DeviceTypeAttributes")
public class DeviceTypeAttributes {

    @XmlElement(name = "DeviceTypeID")
    protected DeviceTypeID deviceTypeID;
    @XmlElement(name = "DeviceTypeAttribute")
    protected List<DeviceTypeAttribute> deviceTypeAttribute;

    /**
     * Gets the value of the deviceTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceTypeID }
     *     
     */
    public DeviceTypeID getDeviceTypeID() {
        return deviceTypeID;
    }

    /**
     * Sets the value of the deviceTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceTypeID }
     *     
     */
    public void setDeviceTypeID(DeviceTypeID value) {
        this.deviceTypeID = value;
    }

    /**
     * Gets the value of the deviceTypeAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceTypeAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceTypeAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceTypeAttribute }
     * 
     * 
     */
    public List<DeviceTypeAttribute> getDeviceTypeAttribute() {
        if (deviceTypeAttribute == null) {
            deviceTypeAttribute = new ArrayList<DeviceTypeAttribute>();
        }
        return this.deviceTypeAttribute;
    }

}
