//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 11:25:29 AM IST 
//


package se.info24.devicejaxbPost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ProductVariantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductVariantName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderMoreBelowThisValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="OrderMoreEventTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderMoreEventTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productVariantID",
    "productVariantName",
    "orderMoreBelowThisValue",
    "orderMoreEventTypeID",
    "orderMoreEventTypeName"
})
@XmlRootElement(name = "ProductLink")
public class ProductLink {

    @XmlElement(name = "ProductVariantID")
    protected String productVariantID;
    @XmlElement(name = "ProductVariantName")
    protected String productVariantName;
    @XmlElement(name = "OrderMoreBelowThisValue")
    protected Double orderMoreBelowThisValue;
    @XmlElement(name = "OrderMoreEventTypeID")
    protected String orderMoreEventTypeID;
    @XmlElement(name = "OrderMoreEventTypeName")
    protected String orderMoreEventTypeName;

    /**
     * Gets the value of the productVariantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductVariantID() {
        return productVariantID;
    }

    /**
     * Sets the value of the productVariantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductVariantID(String value) {
        this.productVariantID = value;
    }

    /**
     * Gets the value of the productVariantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductVariantName() {
        return productVariantName;
    }

    /**
     * Sets the value of the productVariantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductVariantName(String value) {
        this.productVariantName = value;
    }

    /**
     * Gets the value of the orderMoreBelowThisValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOrderMoreBelowThisValue() {
        return orderMoreBelowThisValue;
    }

    /**
     * Sets the value of the orderMoreBelowThisValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOrderMoreBelowThisValue(Double value) {
        this.orderMoreBelowThisValue = value;
    }

    /**
     * Gets the value of the orderMoreEventTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderMoreEventTypeID() {
        return orderMoreEventTypeID;
    }

    /**
     * Sets the value of the orderMoreEventTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderMoreEventTypeID(String value) {
        this.orderMoreEventTypeID = value;
    }

    /**
     * Gets the value of the orderMoreEventTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderMoreEventTypeName() {
        return orderMoreEventTypeName;
    }

    /**
     * Sets the value of the orderMoreEventTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderMoreEventTypeName(String value) {
        this.orderMoreEventTypeName = value;
    }

}
