//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 11:25:29 AM IST 
//


package se.info24.devicejaxbPost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="WarningLowValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="WarningLowEventTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WarningLowEventTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WarningHighValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="WarningHighEventTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WarningHighEventTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "warningLowValue",
    "warningLowEventTypeID",
    "warningLowEventTypeName",
    "warningHighValue",
    "warningHighEventTypeID",
    "warningHighEventTypeName"
})
@XmlRootElement(name = "WarningLevels")
public class WarningLevels {

    @XmlElement(name = "WarningLowValue")
    protected Double warningLowValue;
    @XmlElement(name = "WarningLowEventTypeID")
    protected String warningLowEventTypeID;
    @XmlElement(name = "WarningLowEventTypeName")
    protected String warningLowEventTypeName;
    @XmlElement(name = "WarningHighValue")
    protected Double warningHighValue;
    @XmlElement(name = "WarningHighEventTypeID")
    protected String warningHighEventTypeID;
    @XmlElement(name = "WarningHighEventTypeName")
    protected String warningHighEventTypeName;

    /**
     * Gets the value of the warningLowValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWarningLowValue() {
        return warningLowValue;
    }

    /**
     * Sets the value of the warningLowValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWarningLowValue(Double value) {
        this.warningLowValue = value;
    }

    /**
     * Gets the value of the warningLowEventTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningLowEventTypeID() {
        return warningLowEventTypeID;
    }

    /**
     * Sets the value of the warningLowEventTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningLowEventTypeID(String value) {
        this.warningLowEventTypeID = value;
    }

    /**
     * Gets the value of the warningLowEventTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningLowEventTypeName() {
        return warningLowEventTypeName;
    }

    /**
     * Sets the value of the warningLowEventTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningLowEventTypeName(String value) {
        this.warningLowEventTypeName = value;
    }

    /**
     * Gets the value of the warningHighValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWarningHighValue() {
        return warningHighValue;
    }

    /**
     * Sets the value of the warningHighValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWarningHighValue(Double value) {
        this.warningHighValue = value;
    }

    /**
     * Gets the value of the warningHighEventTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningHighEventTypeID() {
        return warningHighEventTypeID;
    }

    /**
     * Sets the value of the warningHighEventTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningHighEventTypeID(String value) {
        this.warningHighEventTypeID = value;
    }

    /**
     * Gets the value of the warningHighEventTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningHighEventTypeName() {
        return warningHighEventTypeName;
    }

    /**
     * Sets the value of the warningHighEventTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningHighEventTypeName(String value) {
        this.warningHighEventTypeName = value;
    }

}
