package se.info24.pojo;
// Generated Apr 28, 2014 4:47:22 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Connectors generated by hbm2java
 */
public class Connectors implements java.io.Serializable {

    private String connectorId;
    private ProductVariants productVariants;
    private DeviceDataItems deviceDataItems;
    private ConnectorTypes connectorTypes;
    private ConnectorAcdc connectorAcdc;
    private ConnectorCurrents connectorCurrents;
    private ConnectorModes connectorModes;
    private ConnectorVoltages connectorVoltages;
    private Device device;
    private String deviceId;
    private String connectorName;
    private String connectorDescription;
    private int sortOrder;
    private String connectorTypeCode;
    private String connectorModeCode;
    private String connectorVoltageCode;
    private String connectorCurrentCode;
    private String connectorAcdccode;
    private String loadBalanceId;
    private int isEnabled;
    private int isVisibleInApi;
    private String publicComment1;
    private String publicComment2;
    private String internalComment;
    private String connectorImageUrl;
    private String floor;
    private String building;
    private String searchTags;
    private String connectorTemplateId;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;

    public Connectors() {
    }

    public Connectors(String connectorId, DeviceDataItems deviceDataItems, String deviceId, String connectorName, int sortOrder, int isEnabled, int isVisibleInApi, String lastUpdatedByUserId) {
        this.connectorId = connectorId;
        this.deviceDataItems = deviceDataItems;
        this.deviceId = deviceId;
        this.connectorName = connectorName;
        this.sortOrder = sortOrder;
        this.isEnabled = isEnabled;
        this.isVisibleInApi = isVisibleInApi;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Connectors(String connectorId, ProductVariants productVariants, DeviceDataItems deviceDataItems, ConnectorTypes connectorTypes, ConnectorAcdc connectorAcdc, ConnectorCurrents connectorCurrents, ConnectorModes connectorModes, ConnectorVoltages connectorVoltages, Device device, String deviceId, String connectorName, String connectorDescription, int sortOrder, String connectorTypeCode, String connectorModeCode, String connectorVoltageCode, String connectorCurrentCode, String connectorAcdccode, String loadBalanceId, int isEnabled, int isVisibleInApi, String publicComment1, String publicComment2, String internalComment, String connectorImageUrl, String floor, String building, String searchTags, String connectorTemplateId, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
        this.connectorId = connectorId;
        this.productVariants = productVariants;
        this.deviceDataItems = deviceDataItems;
        this.connectorTypes = connectorTypes;
        this.connectorAcdc = connectorAcdc;
        this.connectorCurrents = connectorCurrents;
        this.connectorModes = connectorModes;
        this.connectorVoltages = connectorVoltages;
        this.device = device;
        this.deviceId = deviceId;
        this.connectorName = connectorName;
        this.connectorDescription = connectorDescription;
        this.sortOrder = sortOrder;
        this.connectorTypeCode = connectorTypeCode;
        this.connectorModeCode = connectorModeCode;
        this.connectorVoltageCode = connectorVoltageCode;
        this.connectorCurrentCode = connectorCurrentCode;
        this.connectorAcdccode = connectorAcdccode;
        this.loadBalanceId = loadBalanceId;
        this.isEnabled = isEnabled;
        this.isVisibleInApi = isVisibleInApi;
        this.publicComment1 = publicComment1;
        this.publicComment2 = publicComment2;
        this.internalComment = internalComment;
        this.connectorImageUrl = connectorImageUrl;
        this.floor = floor;
        this.building = building;
        this.searchTags = searchTags;
        this.connectorTemplateId = connectorTemplateId;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    public String getConnectorId() {
        return this.connectorId;
    }

    public void setConnectorId(String connectorId) {
        this.connectorId = connectorId;
    }

    public ProductVariants getProductVariants() {
        return this.productVariants;
    }

    public void setProductVariants(ProductVariants productVariants) {
        this.productVariants = productVariants;
    }

    public DeviceDataItems getDeviceDataItems() {
        return this.deviceDataItems;
    }

    public void setDeviceDataItems(DeviceDataItems deviceDataItems) {
        this.deviceDataItems = deviceDataItems;
    }

    public ConnectorTypes getConnectorTypes() {
        return this.connectorTypes;
    }

    public void setConnectorTypes(ConnectorTypes connectorTypes) {
        this.connectorTypes = connectorTypes;
    }

    public ConnectorAcdc getConnectorAcdc() {
        return this.connectorAcdc;
    }

    public void setConnectorAcdc(ConnectorAcdc connectorAcdc) {
        this.connectorAcdc = connectorAcdc;
    }

    public ConnectorCurrents getConnectorCurrents() {
        return this.connectorCurrents;
    }

    public void setConnectorCurrents(ConnectorCurrents connectorCurrents) {
        this.connectorCurrents = connectorCurrents;
    }

    public ConnectorModes getConnectorModes() {
        return this.connectorModes;
    }

    public void setConnectorModes(ConnectorModes connectorModes) {
        this.connectorModes = connectorModes;
    }

    public ConnectorVoltages getConnectorVoltages() {
        return this.connectorVoltages;
    }

    public void setConnectorVoltages(ConnectorVoltages connectorVoltages) {
        this.connectorVoltages = connectorVoltages;
    }

    public Device getDevice() {
        return device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    public String getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getConnectorName() {
        return this.connectorName;
    }

    public void setConnectorName(String connectorName) {
        this.connectorName = connectorName;
    }

    public String getConnectorDescription() {
        return this.connectorDescription;
    }

    public void setConnectorDescription(String connectorDescription) {
        this.connectorDescription = connectorDescription;
    }

    public int getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getConnectorTypeCode() {
        return this.connectorTypeCode;
    }

    public void setConnectorTypeCode(String connectorTypeCode) {
        this.connectorTypeCode = connectorTypeCode;
    }

    public String getConnectorModeCode() {
        return this.connectorModeCode;
    }

    public void setConnectorModeCode(String connectorModeCode) {
        this.connectorModeCode = connectorModeCode;
    }

    public String getConnectorVoltageCode() {
        return this.connectorVoltageCode;
    }

    public void setConnectorVoltageCode(String connectorVoltageCode) {
        this.connectorVoltageCode = connectorVoltageCode;
    }

    public String getConnectorCurrentCode() {
        return this.connectorCurrentCode;
    }

    public void setConnectorCurrentCode(String connectorCurrentCode) {
        this.connectorCurrentCode = connectorCurrentCode;
    }

    public String getConnectorAcdccode() {
        return this.connectorAcdccode;
    }

    public void setConnectorAcdccode(String connectorAcdccode) {
        this.connectorAcdccode = connectorAcdccode;
    }

    public String getLoadBalanceId() {
        return this.loadBalanceId;
    }

    public void setLoadBalanceId(String loadBalanceId) {
        this.loadBalanceId = loadBalanceId;
    }

    public int getIsEnabled() {
        return this.isEnabled;
    }

    public void setIsEnabled(int isEnabled) {
        this.isEnabled = isEnabled;
    }

    public int getIsVisibleInApi() {
        return this.isVisibleInApi;
    }

    public void setIsVisibleInApi(int isVisibleInApi) {
        this.isVisibleInApi = isVisibleInApi;
    }

    public String getPublicComment1() {
        return this.publicComment1;
    }

    public void setPublicComment1(String publicComment1) {
        this.publicComment1 = publicComment1;
    }

    public String getPublicComment2() {
        return this.publicComment2;
    }

    public void setPublicComment2(String publicComment2) {
        this.publicComment2 = publicComment2;
    }

    public String getInternalComment() {
        return this.internalComment;
    }

    public void setInternalComment(String internalComment) {
        this.internalComment = internalComment;
    }

    public String getConnectorImageUrl() {
        return this.connectorImageUrl;
    }

    public void setConnectorImageUrl(String connectorImageUrl) {
        this.connectorImageUrl = connectorImageUrl;
    }

    public String getFloor() {
        return this.floor;
    }

    public void setFloor(String floor) {
        this.floor = floor;
    }

    public String getBuilding() {
        return this.building;
    }

    public void setBuilding(String building) {
        this.building = building;
    }

    public String getSearchTags() {
        return this.searchTags;
    }

    public void setSearchTags(String searchTags) {
        this.searchTags = searchTags;
    }

    public String getConnectorTemplateId() {
        return this.connectorTemplateId;
    }

    public void setConnectorTemplateId(String connectorTemplateId) {
        this.connectorTemplateId = connectorTemplateId;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}


