package se.info24.pojo;
// Generated Jun 11, 2014 11:24:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ContentCategoriesInGroups generated by hbm2java
 */
public class ContentCategoriesInGroups  implements java.io.Serializable {


     private ContentCategoriesInGroupsId id;
     private Groups groups;
     private ContentCategories contentCategories;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public ContentCategoriesInGroups() {
    }

	
    public ContentCategoriesInGroups(ContentCategoriesInGroupsId id, Groups groups, ContentCategories contentCategories, String lastUpdatedByUserId) {
        this.id = id;
        this.groups = groups;
        this.contentCategories = contentCategories;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public ContentCategoriesInGroups(ContentCategoriesInGroupsId id, Groups groups, ContentCategories contentCategories, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.groups = groups;
       this.contentCategories = contentCategories;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public ContentCategoriesInGroupsId getId() {
        return this.id;
    }
    
    public void setId(ContentCategoriesInGroupsId id) {
        this.id = id;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public ContentCategories getContentCategories() {
        return this.contentCategories;
    }
    
    public void setContentCategories(ContentCategories contentCategories) {
        this.contentCategories = contentCategories;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


