package se.info24.pojo;
// Generated Oct 17, 2012 5:59:40 PM by Hibernate Tools 3.2.1.GA



/**
 * GroupProductComponentsId generated by hbm2java
 */
public class GroupProductComponentsId  implements java.io.Serializable {


     private String groupId;
     private String componentId;

    public GroupProductComponentsId() {
    }

    public GroupProductComponentsId(String groupId, String componentId) {
       this.groupId = groupId;
       this.componentId = componentId;
    }
   
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getComponentId() {
        return this.componentId;
    }
    
    public void setComponentId(String componentId) {
        this.componentId = componentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupProductComponentsId) ) return false;
		 GroupProductComponentsId castOther = ( GroupProductComponentsId ) other; 
         
		 return ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) )
 && ( (this.getComponentId()==castOther.getComponentId()) || ( this.getComponentId()!=null && castOther.getComponentId()!=null && this.getComponentId().equals(castOther.getComponentId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         result = 37 * result + ( getComponentId() == null ? 0 : this.getComponentId().hashCode() );
         return result;
   }   


}


