package se.info24.pojo;
// Generated Oct 4, 2012 10:52:52 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * ObjectGroupTranslations generated by hbm2java
 */
public class ObjectGroupTranslations  implements java.io.Serializable {


     private ObjectGroupTranslationsId id;
     private ObjectGroups objectGroups;
     private String objectGroupName;
     private String objectGroupDescription;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public ObjectGroupTranslations() {
    }

	
    public ObjectGroupTranslations(ObjectGroupTranslationsId id, ObjectGroups objectGroups, String objectGroupName) {
        this.id = id;
        this.objectGroups = objectGroups;
        this.objectGroupName =  objectGroupName;
    }
    public ObjectGroupTranslations(ObjectGroupTranslationsId id, ObjectGroups objectGroups, String objectGroupName, String objectGroupDescription, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.objectGroups = objectGroups;
       this.objectGroupName = objectGroupName;
       this.objectGroupDescription = objectGroupDescription;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public ObjectGroupTranslationsId getId() {
        return this.id;
    }
    
    public void setId(ObjectGroupTranslationsId id) {
        this.id = id;
    }
    public ObjectGroups getObjectGroups() {
        return this.objectGroups;
    }
    
    public void setObjectGroups(ObjectGroups objectGroups) {
        this.objectGroups = objectGroups;
    }
    public String getObjectGroupName() {
        return this.objectGroupName;
    }
    
    public void setObjectGroupName(String objectGroupName) {
        this.objectGroupName = objectGroupName;
    }
    public String getObjectGroupDescription() {
        return this.objectGroupDescription;
    }
    
    public void setObjectGroupDescription(String objectGroupDescription) {
        this.objectGroupDescription = objectGroupDescription;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


