package se.info24.pojo;
// Generated Aug 24, 2011 11:31:48 AM by Hibernate Tools 3.2.1.GA



/**
 * ObjectContentCategorySubscriptionsId generated by hbm2java
 */
public class ObjectContentCategorySubscriptionsId  implements java.io.Serializable {


     private String objectId;
     private String contentCategoryId;

    public ObjectContentCategorySubscriptionsId() {
    }

    public ObjectContentCategorySubscriptionsId(String objectId, String contentCategoryId) {
       this.objectId = objectId;
       this.contentCategoryId = contentCategoryId;
    }
   
    public String getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }
    public String getContentCategoryId() {
        return this.contentCategoryId;
    }
    
    public void setContentCategoryId(String contentCategoryId) {
        this.contentCategoryId = contentCategoryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObjectContentCategorySubscriptionsId) ) return false;
		 ObjectContentCategorySubscriptionsId castOther = ( ObjectContentCategorySubscriptionsId ) other; 
         
		 return ( (this.getObjectId()==castOther.getObjectId()) || ( this.getObjectId()!=null && castOther.getObjectId()!=null && this.getObjectId().equals(castOther.getObjectId()) ) )
 && ( (this.getContentCategoryId()==castOther.getContentCategoryId()) || ( this.getContentCategoryId()!=null && castOther.getContentCategoryId()!=null && this.getContentCategoryId().equals(castOther.getContentCategoryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getObjectId() == null ? 0 : this.getObjectId().hashCode() );
         result = 37 * result + ( getContentCategoryId() == null ? 0 : this.getContentCategoryId().hashCode() );
         return result;
   }   


}


