package se.info24.pojo;
// Generated Jun 26, 2012 3:24:36 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ObjectUsageUnits generated by hbm2java
 */
public class ObjectUsageUnits implements java.io.Serializable {

    private String usageUnitId;
    private String usageUnitName;
    private String usageUnitDescription;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;
    private Set chargeTypeses = new HashSet(0);
    private Set measurementTypeses = new HashSet(0);

    public ObjectUsageUnits() {
    }

    public ObjectUsageUnits(String usageUnitId) {
        this.usageUnitId = usageUnitId;
    }

    public ObjectUsageUnits(String usageUnitId, String usageUnitName, String usageUnitDescription, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set chargeTypeses, Set measurementTypeses) {
        this.usageUnitId = usageUnitId;
        this.usageUnitName = usageUnitName;
        this.usageUnitDescription = usageUnitDescription;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.chargeTypeses = chargeTypeses;
        this.measurementTypeses = measurementTypeses;
    }

    public String getUsageUnitId() {
        return this.usageUnitId;
    }

    public void setUsageUnitId(String usageUnitId) {
        this.usageUnitId = usageUnitId;
    }

    public String getUsageUnitName() {
        return this.usageUnitName;
    }

    public void setUsageUnitName(String usageUnitName) {
        this.usageUnitName = usageUnitName;
    }

    public String getUsageUnitDescription() {
        return this.usageUnitDescription;
    }

    public void setUsageUnitDescription(String usageUnitDescription) {
        this.usageUnitDescription = usageUnitDescription;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getChargeTypeses() {
        return this.chargeTypeses;
    }

    public void setChargeTypeses(Set chargeTypeses) {
        this.chargeTypeses = chargeTypeses;
    }

    public Set getMeasurementTypeses() {
        return this.measurementTypeses;
    }

    public void setMeasurementTypeses(Set measurementTypeses) {
        this.measurementTypeses = measurementTypeses;
    }
}


