package se.info24.pojo;
// Generated Jan 8, 2013 3:53:44 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * ProductVariantAttributes generated by hbm2java
 */
public class ProductVariantAttributes  implements java.io.Serializable {


     private String productVariantAttributeId;
     private String productVariantId;
     private String attributeName;
     private String attributeValue;
     private String userId;
     private Date createdDate;
     private Date updatedDate;

    public ProductVariantAttributes() {
    }

	
    public ProductVariantAttributes(String productVariantAttributeId, String productVariantId, String attributeName) {
        this.productVariantAttributeId = productVariantAttributeId;
        this.productVariantId = productVariantId;
        this.attributeName = attributeName;
    }
    public ProductVariantAttributes(String productVariantAttributeId, String productVariantId, String attributeName, String attributeValue, String userId, Date createdDate, Date updatedDate) {
       this.productVariantAttributeId = productVariantAttributeId;
       this.productVariantId = productVariantId;
       this.attributeName = attributeName;
       this.attributeValue = attributeValue;
       this.userId = userId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public String getProductVariantAttributeId() {
        return this.productVariantAttributeId;
    }
    
    public void setProductVariantAttributeId(String productVariantAttributeId) {
        this.productVariantAttributeId = productVariantAttributeId;
    }
    public String getProductVariantId() {
        return this.productVariantId;
    }
    
    public void setProductVariantId(String productVariantId) {
        this.productVariantId = productVariantId;
    }
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


