package se.info24.pojo;
// Generated Nov 24, 2012 2:20:28 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RoutingTable generated by hbm2java
 */
public class RoutingTable  implements java.io.Serializable {


     private String routeId;
     private RoutingTable routingTable;
     private Routers routers;
     private Groups groups;
     private ValidationDataType validationDataType;
     private ValidationExpressions validationExpressions;
     private MessageTypes messageTypes;
     private MessageItems messageItems;
     private Channels channels;
     private String routeName;
     private String routeDescription;
     private String validationData;
     private Date activeFromDate;
     private Integer routeEnabled;
     private String userId;
     private Date createdDate;
     private Date updatedDate;
     private Set routingTables = new HashSet(0);

    public RoutingTable() {
    }

	
    public RoutingTable(String routeId, Groups groups, MessageTypes messageTypes, String routeName) {
        this.routeId = routeId;
        this.groups = groups;
        this.messageTypes = messageTypes;
        this.routeName = routeName;
    }
    public RoutingTable(String routeId, RoutingTable routingTable, Routers routers, Groups groups, ValidationDataType validationDataType, ValidationExpressions validationExpressions, MessageTypes messageTypes, MessageItems messageItems, Channels channels, String routeName, String routeDescription, String validationData, Date activeFromDate, Integer routeEnabled, String userId, Date createdDate, Date updatedDate, Set routingTables) {
       this.routeId = routeId;
       this.routingTable = routingTable;
       this.routers = routers;
       this.groups = groups;
       this.validationDataType = validationDataType;
       this.validationExpressions = validationExpressions;
       this.messageTypes = messageTypes;
       this.messageItems = messageItems;
       this.channels = channels;
       this.routeName = routeName;
       this.routeDescription = routeDescription;
       this.validationData = validationData;
       this.activeFromDate = activeFromDate;
       this.routeEnabled = routeEnabled;
       this.userId = userId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.routingTables = routingTables;
    }
   
    public String getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(String routeId) {
        this.routeId = routeId;
    }
    public RoutingTable getRoutingTable() {
        return this.routingTable;
    }
    
    public void setRoutingTable(RoutingTable routingTable) {
        this.routingTable = routingTable;
    }
    public Routers getRouters() {
        return this.routers;
    }
    
    public void setRouters(Routers routers) {
        this.routers = routers;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public ValidationDataType getValidationDataType() {
        return this.validationDataType;
    }
    
    public void setValidationDataType(ValidationDataType validationDataType) {
        this.validationDataType = validationDataType;
    }
    public ValidationExpressions getValidationExpressions() {
        return this.validationExpressions;
    }
    
    public void setValidationExpressions(ValidationExpressions validationExpressions) {
        this.validationExpressions = validationExpressions;
    }
    public MessageTypes getMessageTypes() {
        return this.messageTypes;
    }
    
    public void setMessageTypes(MessageTypes messageTypes) {
        this.messageTypes = messageTypes;
    }
    public MessageItems getMessageItems() {
        return this.messageItems;
    }
    
    public void setMessageItems(MessageItems messageItems) {
        this.messageItems = messageItems;
    }
    public Channels getChannels() {
        return this.channels;
    }
    
    public void setChannels(Channels channels) {
        this.channels = channels;
    }
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }
    public String getRouteDescription() {
        return this.routeDescription;
    }
    
    public void setRouteDescription(String routeDescription) {
        this.routeDescription = routeDescription;
    }
    public String getValidationData() {
        return this.validationData;
    }
    
    public void setValidationData(String validationData) {
        this.validationData = validationData;
    }
    public Date getActiveFromDate() {
        return this.activeFromDate;
    }
    
    public void setActiveFromDate(Date activeFromDate) {
        this.activeFromDate = activeFromDate;
    }
    public Integer getRouteEnabled() {
        return this.routeEnabled;
    }
    
    public void setRouteEnabled(Integer routeEnabled) {
        this.routeEnabled = routeEnabled;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Set getRoutingTables() {
        return this.routingTables;
    }
    
    public void setRoutingTables(Set routingTables) {
        this.routingTables = routingTables;
    }




}


