package se.info24.pojo;
// Generated Jun 5, 2013 11:23:30 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * SupportImpactTranslations generated by hbm2java
 */
public class SupportImpactTranslations  implements java.io.Serializable {


     private SupportImpactTranslationsId id;
     private String supportCaseImpactName;
     private String supportCaseImpactDescription;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public SupportImpactTranslations() {
    }

	
    public SupportImpactTranslations(SupportImpactTranslationsId id, String supportCaseImpactName, String lastUpdatedByUserId) {
        this.id = id;
        this.supportCaseImpactName = supportCaseImpactName;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public SupportImpactTranslations(SupportImpactTranslationsId id, String supportCaseImpactName, String supportCaseImpactDescription, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.supportCaseImpactName = supportCaseImpactName;
       this.supportCaseImpactDescription = supportCaseImpactDescription;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public SupportImpactTranslationsId getId() {
        return this.id;
    }
    
    public void setId(SupportImpactTranslationsId id) {
        this.id = id;
    }
    public String getSupportCaseImpactName() {
        return this.supportCaseImpactName;
    }
    
    public void setSupportCaseImpactName(String supportCaseImpactName) {
        this.supportCaseImpactName = supportCaseImpactName;
    }
    public String getSupportCaseImpactDescription() {
        return this.supportCaseImpactDescription;
    }
    
    public void setSupportCaseImpactDescription(String supportCaseImpactDescription) {
        this.supportCaseImpactDescription = supportCaseImpactDescription;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


