package se.info24.pojo;
// Generated Dec 11, 2013 10:32:58 AM by Hibernate Tools 3.2.1.GA



/**
 * SupportCaseContentLinksId generated by hbm2java
 */
public class SupportCaseContentLinksId  implements java.io.Serializable {


     private String supportCaseId;
     private String contentCategoryId;

    public SupportCaseContentLinksId() {
    }

    public SupportCaseContentLinksId(String supportCaseId, String contentCategoryId) {
       this.supportCaseId = supportCaseId;
       this.contentCategoryId = contentCategoryId;
    }
   
    public String getSupportCaseId() {
        return this.supportCaseId;
    }
    
    public void setSupportCaseId(String supportCaseId) {
        this.supportCaseId = supportCaseId;
    }
    public String getContentCategoryId() {
        return this.contentCategoryId;
    }
    
    public void setContentCategoryId(String contentCategoryId) {
        this.contentCategoryId = contentCategoryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SupportCaseContentLinksId) ) return false;
		 SupportCaseContentLinksId castOther = ( SupportCaseContentLinksId ) other; 
         
		 return ( (this.getSupportCaseId()==castOther.getSupportCaseId()) || ( this.getSupportCaseId()!=null && castOther.getSupportCaseId()!=null && this.getSupportCaseId().equals(castOther.getSupportCaseId()) ) )
 && ( (this.getContentCategoryId()==castOther.getContentCategoryId()) || ( this.getContentCategoryId()!=null && castOther.getContentCategoryId()!=null && this.getContentCategoryId().equals(castOther.getContentCategoryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSupportCaseId() == null ? 0 : this.getSupportCaseId().hashCode() );
         result = 37 * result + ( getContentCategoryId() == null ? 0 : this.getContentCategoryId().hashCode() );
         return result;
   }   


}


