package se.info24.pojo;
// Generated Sep 24, 2013 1:11:02 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * UnitTranslations generated by hbm2java
 */
public class UnitTranslations  implements java.io.Serializable {


     private UnitTranslationsId id;
     private Country country;
     private Unit unit;
     private String unitName;
     private String unitShortName;
     private String unitDescription;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public UnitTranslations() {
    }

	
    public UnitTranslations(UnitTranslationsId id, Country country, Unit unit, String unitName, String unitShortName) {
        this.id = id;
        this.country = country;
        this.unit = unit;
        this.unitName = unitName;
        this.unitShortName = unitShortName;
    }
    public UnitTranslations(UnitTranslationsId id, Country country, Unit unit, String unitName, String unitShortName, String unitDescription, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.country = country;
       this.unit = unit;
       this.unitName = unitName;
       this.unitShortName = unitShortName;
       this.unitDescription = unitDescription;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public UnitTranslationsId getId() {
        return this.id;
    }
    
    public void setId(UnitTranslationsId id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    public String getUnitShortName() {
        return this.unitShortName;
    }
    
    public void setUnitShortName(String unitShortName) {
        this.unitShortName = unitShortName;
    }
    public String getUnitDescription() {
        return this.unitDescription;
    }
    
    public void setUnitDescription(String unitDescription) {
        this.unitDescription = unitDescription;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


