package se.info24.pojo;
// Generated Nov 4, 2011 1:10:11 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAlias generated by hbm2java
 */
public class UserAlias implements java.io.Serializable {

    private String userAliasId;
    private UserAliasTypes userAliasTypes;
    private String userAlias;
    private String userId;
    private String groupId;
    private String firstName;
    private String lastName;
    private String userEmail;
    private String userMobilePhone;
    private String socialSecurityNumber;
    private Integer isEnabled;
    private Date activeFromDate;
    private Date activeToDate;
    private Date firstUseDate;
    private Date lastUseDate;
    private Double creditAmount;
    private Integer creditAmountCurrencyId;
    private Integer credits;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;
    private Date extVerify;
    private Set userAliasDetailses = new HashSet(0);
    private Set ogmuserAliases = new HashSet(0);

    public UserAlias() {
    }

    public UserAlias(String userAliasId, UserAliasTypes userAliasTypes, String userAlias) {
        this.userAliasId = userAliasId;
        this.userAliasTypes = userAliasTypes;
        this.userAlias = userAlias;
    }

    public UserAlias(String userAliasId, UserAliasTypes userAliasTypes, String userAlias, String userId, String groupId, String firstName, String lastName, String userEmail, String userMobilePhone, String socialSecurityNumber, Integer isEnabled, Date activeFromDate, Date activeToDate, Date firstUseDate, Date lastUseDate, Double creditAmount, Integer creditAmountCurrencyId, Integer credits, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Date extVerify, Set userAliasDetailses, Set ogmuserAliases) {
        this.userAliasId = userAliasId;
        this.userAliasTypes = userAliasTypes;
        this.userAlias = userAlias;
        this.userId = userId;
        this.groupId = groupId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userEmail = userEmail;
        this.userMobilePhone = userMobilePhone;
        this.socialSecurityNumber = socialSecurityNumber;
        this.isEnabled = isEnabled;
        this.activeFromDate = activeFromDate;
        this.activeToDate = activeToDate;
        this.firstUseDate = firstUseDate;
        this.lastUseDate = lastUseDate;
        this.creditAmount = creditAmount;
        this.creditAmountCurrencyId = creditAmountCurrencyId;
        this.credits = credits;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.extVerify = extVerify;
        this.userAliasDetailses = userAliasDetailses;
        this.ogmuserAliases = ogmuserAliases;
    }

    public String getUserAliasId() {
        return this.userAliasId;
    }

    public void setUserAliasId(String userAliasId) {
        this.userAliasId = userAliasId;
    }

    public UserAliasTypes getUserAliasTypes() {
        return this.userAliasTypes;
    }

    public void setUserAliasTypes(UserAliasTypes userAliasTypes) {
        this.userAliasTypes = userAliasTypes;
    }

    public String getUserAlias() {
        return this.userAlias;
    }

    public void setUserAlias(String userAlias) {
        this.userAlias = userAlias;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserMobilePhone() {
        return this.userMobilePhone;
    }

    public void setUserMobilePhone(String userMobilePhone) {
        this.userMobilePhone = userMobilePhone;
    }

    public String getSocialSecurityNumber() {
        return this.socialSecurityNumber;
    }

    public void setSocialSecurityNumber(String socialSecurityNumber) {
        this.socialSecurityNumber = socialSecurityNumber;
    }

    public Integer getIsEnabled() {
        return this.isEnabled;
    }

    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    public Date getActiveFromDate() {
        return this.activeFromDate;
    }

    public void setActiveFromDate(Date activeFromDate) {
        this.activeFromDate = activeFromDate;
    }

    public Date getActiveToDate() {
        return this.activeToDate;
    }

    public void setActiveToDate(Date activeToDate) {
        this.activeToDate = activeToDate;
    }

    public Date getFirstUseDate() {
        return this.firstUseDate;
    }

    public void setFirstUseDate(Date firstUseDate) {
        this.firstUseDate = firstUseDate;
    }

    public Date getLastUseDate() {
        return this.lastUseDate;
    }

    public void setLastUseDate(Date lastUseDate) {
        this.lastUseDate = lastUseDate;
    }

    public Double getCreditAmount() {
        return this.creditAmount;
    }

    public void setCreditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
    }

    public Integer getCreditAmountCurrencyId() {
        return this.creditAmountCurrencyId;
    }

    public void setCreditAmountCurrencyId(Integer creditAmountCurrencyId) {
        this.creditAmountCurrencyId = creditAmountCurrencyId;
    }

    public Integer getCredits() {
        return this.credits;
    }

    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getExtVerify() {
        return this.extVerify;
    }

    public void setExtVerify(Date extVerify) {
        this.extVerify = extVerify;
    }

    public Set getUserAliasDetailses() {
        return this.userAliasDetailses;
    }

    public void setUserAliasDetailses(Set userAliasDetailses) {
        this.userAliasDetailses = userAliasDetailses;
    }

    public Set getOgmuserAliases() {
        return this.ogmuserAliases;
    }

    public void setOgmuserAliases(Set ogmuserAliases) {
        this.ogmuserAliases = ogmuserAliases;
    }
}


