package se.info24.pojo;
// Generated Dec 18, 2013 11:55:13 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AgreementItemTypes generated by hbm2java
 */
public class AgreementItemTypes implements java.io.Serializable {

    private String agreementItemTypeId;
    private String objectCode;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;
    private Set agreementItemTypeTranslationses = new HashSet(0);
    private Set agreementItemses = new HashSet(0);

    public AgreementItemTypes() {
    }

    public AgreementItemTypes(String agreementItemTypeId, String objectCode) {
        this.agreementItemTypeId = agreementItemTypeId;
        this.objectCode = objectCode;
    }

    public AgreementItemTypes(String agreementItemTypeId, String objectCode, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set agreementItemTypeTranslationses, Set agreementItemses) {
        this.agreementItemTypeId = agreementItemTypeId;
        this.objectCode = objectCode;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.agreementItemTypeTranslationses = agreementItemTypeTranslationses;
        this.agreementItemses = agreementItemses;
    }

    public String getAgreementItemTypeId() {
        return this.agreementItemTypeId;
    }

    public void setAgreementItemTypeId(String agreementItemTypeId) {
        this.agreementItemTypeId = agreementItemTypeId;
    }

    public String getObjectCode() {
        return this.objectCode;
    }

    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getAgreementItemTypeTranslationses() {
        return this.agreementItemTypeTranslationses;
    }

    public void setAgreementItemTypeTranslationses(Set agreementItemTypeTranslationses) {
        this.agreementItemTypeTranslationses = agreementItemTypeTranslationses;
    }

    public Set getAgreementItemses() {
        return this.agreementItemses;
    }

    public void setAgreementItemses(Set agreementItemses) {
        this.agreementItemses = agreementItemses;
    }
}


