package se.info24.pojo;
// Generated Aug 21, 2014 12:56:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Buildings generated by hbm2java
 */
public class Buildings  implements java.io.Serializable {


     private String buildingId;
     private Agreements agreements;
     private Country country;
     private BuildingTypes buildingTypes;
     private String buildingParentId;
     private String buildingName;
     private String buildingDescription;
     private String ownerGroupId;
     private String usedByGroupId;
     private String containerId;
     private String propertyCode;
     private String buildingNumber;
     private String buildingCode;
     private Integer shareOfParent;
     private String floorLevel;
     private BigDecimal area;
     private String areaUnit;
     private BigDecimal volume;
     private String volumeUnit;
     private Integer rating;
     private Integer isNonSmoking;
     private Integer isPublicAccess;
     private Integer isOpen;
     private Integer isInEmergencyMode;
     private Integer isPetsAllowed;
     private String street1;
     private String street2;
     private String zipCode;
     private String city;
     private String state;
     private String region;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private BigDecimal altitude;
     private String layoutImageUrl;
     private String websiteUrl;
     private Integer climatePricePreference;
     private Integer userCanChangeClimatePricePref;
     private String energyMeterDeviceId;
     private String heatMeterDeviceId;
     private String waterMeterDeviceId;
     private String gasMeterDeviceId;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;
     private Set roomses = new HashSet(0);
     private Set buildingDeviceses = new HashSet(0);

    public Buildings() {
    }

    public Buildings(String buildingId) {
        this.buildingId = buildingId;
    }

	
    public Buildings(String buildingId, Agreements agreements, BuildingTypes buildingTypes, String buildingName, String ownerGroupId, String lastUpdatedByUserId) {
        this.buildingId = buildingId;
        this.agreements = agreements;
        this.buildingTypes = buildingTypes;
        this.buildingName = buildingName;
        this.ownerGroupId = ownerGroupId;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Buildings(String buildingId, Agreements agreements, Country country, BuildingTypes buildingTypes, String buildingParentId, String buildingName, String buildingDescription, String ownerGroupId, String usedByGroupId, String containerId, String propertyCode, String buildingNumber, String buildingCode, Integer shareOfParent, String floorLevel, BigDecimal area, String areaUnit, BigDecimal volume, String volumeUnit, Integer rating, Integer isNonSmoking, Integer isPublicAccess, Integer isOpen, Integer isInEmergencyMode, String street1, String street2, String zipCode, String city, String state, String region, BigDecimal latitude, BigDecimal longitude, BigDecimal altitude, String layoutImageUrl, String websiteUrl, Integer climatePricePreference, String energyMeterDeviceId, String heatMeterDeviceId, String waterMeterDeviceId, String gasMeterDeviceId, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set roomses, Set buildingDeviceses) {
       this.buildingId = buildingId;
       this.agreements = agreements;
       this.country = country;
       this.buildingTypes = buildingTypes;
       this.buildingParentId = buildingParentId;
       this.buildingName = buildingName;
       this.buildingDescription = buildingDescription;
       this.ownerGroupId = ownerGroupId;
       this.usedByGroupId = usedByGroupId;
       this.containerId = containerId;
       this.propertyCode = propertyCode;
       this.buildingNumber = buildingNumber;
       this.buildingCode = buildingCode;
       this.shareOfParent = shareOfParent;
       this.floorLevel = floorLevel;
       this.area = area;
       this.areaUnit = areaUnit;
       this.volume = volume;
       this.volumeUnit = volumeUnit;
       this.rating = rating;
       this.isNonSmoking = isNonSmoking;
       this.isPublicAccess = isPublicAccess;
       this.isOpen = isOpen;
       this.isInEmergencyMode = isInEmergencyMode;
       this.street1 = street1;
       this.street2 = street2;
       this.zipCode = zipCode;
       this.city = city;
       this.state = state;
       this.region = region;
       this.latitude = latitude;
       this.longitude = longitude;
       this.altitude = altitude;
       this.layoutImageUrl = layoutImageUrl;
       this.websiteUrl = websiteUrl;
       this.climatePricePreference = climatePricePreference;
       this.energyMeterDeviceId = energyMeterDeviceId;
       this.heatMeterDeviceId = heatMeterDeviceId;
       this.waterMeterDeviceId = waterMeterDeviceId;
       this.gasMeterDeviceId = gasMeterDeviceId;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.roomses = roomses;
       this.buildingDeviceses = buildingDeviceses;
    }

    public Integer getUserCanChangeClimatePricePref() {
        return userCanChangeClimatePricePref;
    }

    public void setUserCanChangeClimatePricePref(Integer userCanChangeClimatePricePref) {
        this.userCanChangeClimatePricePref = userCanChangeClimatePricePref;
    }

    

    public Integer getIsPetsAllowed() {
        return isPetsAllowed;
    }

    public void setIsPetsAllowed(Integer isPetsAllowed) {
        this.isPetsAllowed = isPetsAllowed;
    }

    
    public String getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId;
    }
    public Agreements getAgreements() {
        return this.agreements;
    }
    
    public void setAgreements(Agreements agreements) {
        this.agreements = agreements;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public BuildingTypes getBuildingTypes() {
        return this.buildingTypes;
    }
    
    public void setBuildingTypes(BuildingTypes buildingTypes) {
        this.buildingTypes = buildingTypes;
    }
    public String getBuildingParentId() {
        return this.buildingParentId;
    }
    
    public void setBuildingParentId(String buildingParentId) {
        this.buildingParentId = buildingParentId;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public String getBuildingDescription() {
        return this.buildingDescription;
    }
    
    public void setBuildingDescription(String buildingDescription) {
        this.buildingDescription = buildingDescription;
    }
    public String getOwnerGroupId() {
        return this.ownerGroupId;
    }
    
    public void setOwnerGroupId(String ownerGroupId) {
        this.ownerGroupId = ownerGroupId;
    }
    public String getUsedByGroupId() {
        return this.usedByGroupId;
    }
    
    public void setUsedByGroupId(String usedByGroupId) {
        this.usedByGroupId = usedByGroupId;
    }
    public String getContainerId() {
        return this.containerId;
    }
    
    public void setContainerId(String containerId) {
        this.containerId = containerId;
    }
    public String getPropertyCode() {
        return this.propertyCode;
    }
    
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode;
    }
    public String getBuildingNumber() {
        return this.buildingNumber;
    }
    
    public void setBuildingNumber(String buildingNumber) {
        this.buildingNumber = buildingNumber;
    }
    public String getBuildingCode() {
        return this.buildingCode;
    }
    
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode;
    }
    public Integer getShareOfParent() {
        return this.shareOfParent;
    }
    
    public void setShareOfParent(Integer shareOfParent) {
        this.shareOfParent = shareOfParent;
    }
    public String getFloorLevel() {
        return this.floorLevel;
    }
    
    public void setFloorLevel(String floorLevel) {
        this.floorLevel = floorLevel;
    }
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }
    public String getAreaUnit() {
        return this.areaUnit;
    }
    
    public void setAreaUnit(String areaUnit) {
        this.areaUnit = areaUnit;
    }
    public BigDecimal getVolume() {
        return this.volume;
    }
    
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }
    public String getVolumeUnit() {
        return this.volumeUnit;
    }
    
    public void setVolumeUnit(String volumeUnit) {
        this.volumeUnit = volumeUnit;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Integer getIsNonSmoking() {
        return this.isNonSmoking;
    }
    
    public void setIsNonSmoking(Integer isNonSmoking) {
        this.isNonSmoking = isNonSmoking;
    }
    public Integer getIsPublicAccess() {
        return this.isPublicAccess;
    }
    
    public void setIsPublicAccess(Integer isPublicAccess) {
        this.isPublicAccess = isPublicAccess;
    }
    public Integer getIsOpen() {
        return this.isOpen;
    }
    
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }
    public Integer getIsInEmergencyMode() {
        return this.isInEmergencyMode;
    }
    
    public void setIsInEmergencyMode(Integer isInEmergencyMode) {
        this.isInEmergencyMode = isInEmergencyMode;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public BigDecimal getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(BigDecimal altitude) {
        this.altitude = altitude;
    }
    public String getLayoutImageUrl() {
        return this.layoutImageUrl;
    }
    
    public void setLayoutImageUrl(String layoutImageUrl) {
        this.layoutImageUrl = layoutImageUrl;
    }
    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }
    public Integer getClimatePricePreference() {
        return this.climatePricePreference;
    }
    
    public void setClimatePricePreference(Integer climatePricePreference) {
        this.climatePricePreference = climatePricePreference;
    }
    public String getEnergyMeterDeviceId() {
        return this.energyMeterDeviceId;
    }
    
    public void setEnergyMeterDeviceId(String energyMeterDeviceId) {
        this.energyMeterDeviceId = energyMeterDeviceId;
    }
    public String getHeatMeterDeviceId() {
        return this.heatMeterDeviceId;
    }
    
    public void setHeatMeterDeviceId(String heatMeterDeviceId) {
        this.heatMeterDeviceId = heatMeterDeviceId;
    }
    public String getWaterMeterDeviceId() {
        return this.waterMeterDeviceId;
    }
    
    public void setWaterMeterDeviceId(String waterMeterDeviceId) {
        this.waterMeterDeviceId = waterMeterDeviceId;
    }
    public String getGasMeterDeviceId() {
        return this.gasMeterDeviceId;
    }
    
    public void setGasMeterDeviceId(String gasMeterDeviceId) {
        this.gasMeterDeviceId = gasMeterDeviceId;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Set getRoomses() {
        return this.roomses;
    }
    
    public void setRoomses(Set roomses) {
        this.roomses = roomses;
    }
    public Set getBuildingDeviceses() {
        return this.buildingDeviceses;
    }
    
    public void setBuildingDeviceses(Set buildingDeviceses) {
        this.buildingDeviceses = buildingDeviceses;
    }




}


