package se.info24.pojo;
// Generated Oct 23, 2013 12:50:59 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * CommandParseTargetsId generated by hbm2java
 */
public class CommandParseTargetsId  implements java.io.Serializable {


     private String commandId;
     private String targetString;

    public CommandParseTargetsId() {
    }

    public CommandParseTargetsId(String commandId, String targetString) {
       this.commandId = commandId;
       this.targetString = targetString;
    }
   
    public String getCommandId() {
        return this.commandId;
    }
    
    public void setCommandId(String commandId) {
        this.commandId = commandId;
    }
    public String getTargetString() {
        return this.targetString;
    }
    
    public void setTargetString(String targetString) {
        this.targetString = targetString;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CommandParseTargetsId) ) return false;
		 CommandParseTargetsId castOther = ( CommandParseTargetsId ) other; 
         
		 return ( (this.getCommandId()==castOther.getCommandId()) || ( this.getCommandId()!=null && castOther.getCommandId()!=null && this.getCommandId().equals(castOther.getCommandId()) ) )
 && ( (this.getTargetString()==castOther.getTargetString()) || ( this.getTargetString()!=null && castOther.getTargetString()!=null && this.getTargetString().equals(castOther.getTargetString()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCommandId() == null ? 0 : this.getCommandId().hashCode() );
         result = 37 * result + ( getTargetString() == null ? 0 : this.getTargetString().hashCode() );
         return result;
   }   


}


