package se.info24.pojo;
// Generated Aug 24, 2012 2:26:58 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeviceTypeCommands generated by hbm2java
 */
public class DeviceTypeCommands implements java.io.Serializable {

    private String deviceTypeCommandId;
    private String deviceTypeCommandParentId;
    private String deviceTypeId;
    private String objectCode;
    private String deviceDataItemId;
    private String dataItemValue;
    private Integer flagUserCanSetValue;
    private Integer flagIsNumericValue;
    private Integer flagIsVisible;
    private Integer flagValueCanBeNull;
    private Integer displayOrder;
    private BigDecimal minNumericValue;
    private BigDecimal maxNumericValue;
    private Integer maxCharsInValue;
    private String valueRexExValidationString;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;
    private Set deviceTypeCommandTranslationses = new HashSet(0);
    private Set deviceCommandScheduleses = new HashSet(0);
    private Set commandParseTargetses = new HashSet(0);

    public DeviceTypeCommands() {
    }

    public DeviceTypeCommands(String deviceTypeCommandId) {
        this.deviceTypeCommandId = deviceTypeCommandId;
    }

    public DeviceTypeCommands(String deviceTypeCommandId, String deviceTypeId, String objectCode, String deviceDataItemId) {
        this.deviceTypeCommandId = deviceTypeCommandId;
        this.deviceTypeId = deviceTypeId;
        this.objectCode = objectCode;
        this.deviceDataItemId = deviceDataItemId;
    }

    public DeviceTypeCommands(String deviceTypeCommandId, String deviceTypeCommandParentId, String deviceTypeId, String objectCode, String deviceDataItemId, String dataItemValue, Integer flagUserCanSetValue, Integer flagIsNumericValue, Integer flagIsVisible, Integer flagValueCanBeNull, Integer displayOrder, BigDecimal minNumericValue, BigDecimal maxNumericValue, Integer maxCharsInValue, String valueRexExValidationString, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set deviceTypeCommandTranslationses, Set deviceCommandScheduleses, Set commandParseTargetses) {
        this.deviceTypeCommandId = deviceTypeCommandId;
        this.deviceTypeCommandParentId = deviceTypeCommandParentId;
        this.deviceTypeId = deviceTypeId;
        this.objectCode = objectCode;
        this.deviceDataItemId = deviceDataItemId;
        this.dataItemValue = dataItemValue;
        this.flagUserCanSetValue = flagUserCanSetValue;
        this.flagIsNumericValue = flagIsNumericValue;
        this.flagIsVisible = flagIsVisible;
        this.flagValueCanBeNull = flagValueCanBeNull;
        this.displayOrder = displayOrder;
        this.minNumericValue = minNumericValue;
        this.maxNumericValue = maxNumericValue;
        this.maxCharsInValue = maxCharsInValue;
        this.valueRexExValidationString = valueRexExValidationString;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.deviceTypeCommandTranslationses = deviceTypeCommandTranslationses;
        this.deviceCommandScheduleses = deviceCommandScheduleses;
        this.commandParseTargetses = commandParseTargetses;
    }

    public String getDeviceTypeCommandId() {
        return this.deviceTypeCommandId;
    }

    public void setDeviceTypeCommandId(String deviceTypeCommandId) {
        this.deviceTypeCommandId = deviceTypeCommandId;
    }

    public String getDeviceTypeCommandParentId() {
        return this.deviceTypeCommandParentId;
    }

    public void setDeviceTypeCommandParentId(String deviceTypeCommandParentId) {
        this.deviceTypeCommandParentId = deviceTypeCommandParentId;
    }

    public String getDeviceTypeId() {
        return this.deviceTypeId;
    }

    public void setDeviceTypeId(String deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    public String getObjectCode() {
        return this.objectCode;
    }

    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }

    public String getDeviceDataItemId() {
        return this.deviceDataItemId;
    }

    public void setDeviceDataItemId(String deviceDataItemId) {
        this.deviceDataItemId = deviceDataItemId;
    }

    public String getDataItemValue() {
        return this.dataItemValue;
    }

    public void setDataItemValue(String dataItemValue) {
        this.dataItemValue = dataItemValue;
    }

    public Integer getFlagUserCanSetValue() {
        return this.flagUserCanSetValue;
    }

    public void setFlagUserCanSetValue(Integer flagUserCanSetValue) {
        this.flagUserCanSetValue = flagUserCanSetValue;
    }

    public Integer getFlagIsNumericValue() {
        return this.flagIsNumericValue;
    }

    public void setFlagIsNumericValue(Integer flagIsNumericValue) {
        this.flagIsNumericValue = flagIsNumericValue;
    }

    public Integer getFlagIsVisible() {
        return this.flagIsVisible;
    }

    public void setFlagIsVisible(Integer flagIsVisible) {
        this.flagIsVisible = flagIsVisible;
    }

    public Integer getFlagValueCanBeNull() {
        return this.flagValueCanBeNull;
    }

    public void setFlagValueCanBeNull(Integer flagValueCanBeNull) {
        this.flagValueCanBeNull = flagValueCanBeNull;
    }

    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    public BigDecimal getMinNumericValue() {
        return this.minNumericValue;
    }

    public void setMinNumericValue(BigDecimal minNumericValue) {
        this.minNumericValue = minNumericValue;
    }

    public BigDecimal getMaxNumericValue() {
        return this.maxNumericValue;
    }

    public void setMaxNumericValue(BigDecimal maxNumericValue) {
        this.maxNumericValue = maxNumericValue;
    }

    public Integer getMaxCharsInValue() {
        return this.maxCharsInValue;
    }

    public void setMaxCharsInValue(Integer maxCharsInValue) {
        this.maxCharsInValue = maxCharsInValue;
    }

    public String getValueRexExValidationString() {
        return this.valueRexExValidationString;
    }

    public void setValueRexExValidationString(String valueRexExValidationString) {
        this.valueRexExValidationString = valueRexExValidationString;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getDeviceTypeCommandTranslationses() {
        return this.deviceTypeCommandTranslationses;
    }

    public void setDeviceTypeCommandTranslationses(Set deviceTypeCommandTranslationses) {
        this.deviceTypeCommandTranslationses = deviceTypeCommandTranslationses;
    }

    public Set getDeviceCommandScheduleses() {
        return this.deviceCommandScheduleses;
    }

    public void setDeviceCommandScheduleses(Set deviceCommandScheduleses) {
        this.deviceCommandScheduleses = deviceCommandScheduleses;
    }

    public Set getCommandParseTargetses() {
        return this.commandParseTargetses;
    }

    public void setCommandParseTargetses(Set commandParseTargetses) {
        this.commandParseTargetses = commandParseTargetses;
    }
}


