package se.info24.pojo;
// Generated Aug 13, 2012 2:28:58 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * GroupVisibleApplicationPackages generated by hbm2java
 */
public class GroupVisibleApplicationPackages  implements java.io.Serializable {


     private GroupVisibleApplicationPackagesId id;
     private ApplicationPackages applicationPackages;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public GroupVisibleApplicationPackages() {
    }

	
    public GroupVisibleApplicationPackages(GroupVisibleApplicationPackagesId id, ApplicationPackages applicationPackages) {
        this.id = id;
        this.applicationPackages = applicationPackages;
    }
    public GroupVisibleApplicationPackages(GroupVisibleApplicationPackagesId id, ApplicationPackages applicationPackages, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.applicationPackages = applicationPackages;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public GroupVisibleApplicationPackagesId getId() {
        return this.id;
    }
    
    public void setId(GroupVisibleApplicationPackagesId id) {
        this.id = id;
    }
    public ApplicationPackages getApplicationPackages() {
        return this.applicationPackages;
    }
    
    public void setApplicationPackages(ApplicationPackages applicationPackages) {
        this.applicationPackages = applicationPackages;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


