package se.info24.pojo;
// Generated Sep 4, 2012 12:18:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * GroupProductVariantSubscriptions generated by hbm2java
 */
public class GroupProductVariantSubscriptions  implements java.io.Serializable {


     private GroupProductVariantSubscriptionsId id;
     private Integer isEnabled;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public GroupProductVariantSubscriptions() {
    }

	
    public GroupProductVariantSubscriptions(GroupProductVariantSubscriptionsId id) {
        this.id = id;
    }
    public GroupProductVariantSubscriptions(GroupProductVariantSubscriptionsId id, Integer isEnabled, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.isEnabled = isEnabled;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public GroupProductVariantSubscriptionsId getId() {
        return this.id;
    }
    
    public void setId(GroupProductVariantSubscriptionsId id) {
        this.id = id;
    }
    public Integer getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


