package se.info24.pojo;
// Generated Mar 13, 2012 10:38:43 AM by Hibernate Tools 3.2.1.GA



/**
 * MeasurementTypeTranslationsId generated by hbm2java
 */
public class MeasurementTypeTranslationsId  implements java.io.Serializable {


     private String measurementTypeId;
     private int countryId;

    public MeasurementTypeTranslationsId() {
    }

    public MeasurementTypeTranslationsId(String measurementTypeId, int countryId) {
       this.measurementTypeId = measurementTypeId;
       this.countryId = countryId;
    }
   
    public String getMeasurementTypeId() {
        return this.measurementTypeId;
    }
    
    public void setMeasurementTypeId(String measurementTypeId) {
        this.measurementTypeId = measurementTypeId;
    }
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MeasurementTypeTranslationsId) ) return false;
		 MeasurementTypeTranslationsId castOther = ( MeasurementTypeTranslationsId ) other; 
         
		 return ( (this.getMeasurementTypeId()==castOther.getMeasurementTypeId()) || ( this.getMeasurementTypeId()!=null && castOther.getMeasurementTypeId()!=null && this.getMeasurementTypeId().equals(castOther.getMeasurementTypeId()) ) )
 && (this.getCountryId()==castOther.getCountryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMeasurementTypeId() == null ? 0 : this.getMeasurementTypeId().hashCode() );
         result = 37 * result + this.getCountryId();
         return result;
   }   


}


