package se.info24.pojo;
// Generated Jun 26, 2012 3:24:36 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PricePlans generated by hbm2java
 */
public class PricePlans implements java.io.Serializable {

    private String pricePlanId;
    private PricePlanTypes pricePlanTypes;
    private String pricePlanName;
    private String pricePlanDescription;
    private String groupId;
    private Date activeFromDate;
    private Date activeToDate;
    private Integer isEnabled;
    private String lastUpdatedByUserId;
    private Date createdDate;
    private Date updatedDate;
    private Set pricePlanVersionses = new HashSet(0);
    private Set<PricePlansInGroups> pricePlansInGroupses = new HashSet<PricePlansInGroups>(0);
    private Set agreementItemses = new HashSet(0);

    public PricePlans() {
    }

    public PricePlans(String pricePlanId, PricePlanTypes pricePlanTypes, String pricePlanName, String groupId, Date activeFromDate, Date activeToDate, String lastUpdatedByUserId) {
        this.pricePlanId = pricePlanId;
        this.pricePlanTypes = pricePlanTypes;
        this.pricePlanName = pricePlanName;
        this.groupId = groupId;
        this.activeFromDate = activeFromDate;
        this.activeToDate = activeToDate;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public PricePlans(String pricePlanId, PricePlanTypes pricePlanTypes, String pricePlanName, String pricePlanDescription, String groupId, Date activeFromDate, Date activeToDate, Integer isEnabled, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set pricePlanVersionses, Set agreementItemses) {
        this.pricePlanId = pricePlanId;
        this.pricePlanTypes = pricePlanTypes;
        this.pricePlanName = pricePlanName;
        this.pricePlanDescription = pricePlanDescription;
        this.groupId = groupId;
        this.activeFromDate = activeFromDate;
        this.activeToDate = activeToDate;
        this.isEnabled = isEnabled;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.pricePlanVersionses = pricePlanVersionses;
        this.agreementItemses = agreementItemses;
    }

    public String getPricePlanId() {
        return this.pricePlanId;
    }

    public Set<PricePlansInGroups> getPricePlansInGroupses() {
        return pricePlansInGroupses;
    }

    public void setPricePlansInGroupses(Set<PricePlansInGroups> pricePlansInGroupses) {
        this.pricePlansInGroupses = pricePlansInGroupses;
    }

    public void setPricePlanId(String pricePlanId) {
        this.pricePlanId = pricePlanId;
    }

    public PricePlanTypes getPricePlanTypes() {
        return this.pricePlanTypes;
    }

    public void setPricePlanTypes(PricePlanTypes pricePlanTypes) {
        this.pricePlanTypes = pricePlanTypes;
    }

    public String getPricePlanName() {
        return this.pricePlanName;
    }

    public void setPricePlanName(String pricePlanName) {
        this.pricePlanName = pricePlanName;
    }

    public String getPricePlanDescription() {
        return this.pricePlanDescription;
    }

    public void setPricePlanDescription(String pricePlanDescription) {
        this.pricePlanDescription = pricePlanDescription;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Date getActiveFromDate() {
        return this.activeFromDate;
    }

    public void setActiveFromDate(Date activeFromDate) {
        this.activeFromDate = activeFromDate;
    }

    public Date getActiveToDate() {
        return this.activeToDate;
    }

    public void setActiveToDate(Date activeToDate) {
        this.activeToDate = activeToDate;
    }

    public Integer getIsEnabled() {
        return this.isEnabled;
    }

    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }

    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getPricePlanVersionses() {
        return this.pricePlanVersionses;
    }

    public void setPricePlanVersionses(Set pricePlanVersionses) {
        this.pricePlanVersionses = pricePlanVersionses;
    }

    public Set getAgreementItemses() {
        return this.agreementItemses;
    }

    public void setAgreementItemses(Set agreementItemses) {
        this.agreementItemses = agreementItemses;
    }
}


