package se.info24.pojo;
// Generated Oct 29, 2012 5:22:24 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceDeviceSubscriptions generated by hbm2java
 */
public class ServiceDeviceSubscriptions implements java.io.Serializable {

    private String serviceDeviceSubscriptionId;
    private Agreements agreements;
    private Services services;
    private ServiceClientLogins serviceClientLogins;
    private Device device;
    private Integer subscriptionEnabled;
    private String serviceSubscriptionAclid;
    private String userId;
    private Date createdDate;
    private Date updatedDate;
    private Set serviceDeviceSettingses = new HashSet(0);

    public ServiceDeviceSubscriptions() {
    }

    public ServiceDeviceSubscriptions(String serviceDeviceSubscriptionId, Services services, Device device) {
        this.serviceDeviceSubscriptionId = serviceDeviceSubscriptionId;
        this.services = services;
        this.device = device;
    }

    public ServiceDeviceSubscriptions(String serviceDeviceSubscriptionId, Agreements agreements, Services services, ServiceClientLogins serviceClientLogins, Device device, Integer subscriptionEnabled, String serviceSubscriptionAclid, String userId, Date createdDate, Date updatedDate, Set serviceDeviceSettingses) {
        this.serviceDeviceSubscriptionId = serviceDeviceSubscriptionId;
        this.agreements = agreements;
        this.services = services;
        this.serviceClientLogins = serviceClientLogins;
        this.device = device;
        this.subscriptionEnabled = subscriptionEnabled;
        this.serviceSubscriptionAclid = serviceSubscriptionAclid;
        this.userId = userId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.serviceDeviceSettingses = serviceDeviceSettingses;
    }

    public String getServiceDeviceSubscriptionId() {
        return this.serviceDeviceSubscriptionId;
    }

    public void setServiceDeviceSubscriptionId(String serviceDeviceSubscriptionId) {
        this.serviceDeviceSubscriptionId = serviceDeviceSubscriptionId;
    }

    public Agreements getAgreements() {
        return this.agreements;
    }

    public void setAgreements(Agreements agreements) {
        this.agreements = agreements;
    }

    public Services getServices() {
        return this.services;
    }

    public void setServices(Services services) {
        this.services = services;
    }

    public ServiceClientLogins getServiceClientLogins() {
        return this.serviceClientLogins;
    }

    public void setServiceClientLogins(ServiceClientLogins serviceClientLogins) {
        this.serviceClientLogins = serviceClientLogins;
    }

    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    public Integer getSubscriptionEnabled() {
        return this.subscriptionEnabled;
    }

    public void setSubscriptionEnabled(Integer subscriptionEnabled) {
        this.subscriptionEnabled = subscriptionEnabled;
    }

    public String getServiceSubscriptionAclid() {
        return this.serviceSubscriptionAclid;
    }

    public void setServiceSubscriptionAclid(String serviceSubscriptionAclid) {
        this.serviceSubscriptionAclid = serviceSubscriptionAclid;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Set getServiceDeviceSettingses() {
        return this.serviceDeviceSettingses;
    }

    public void setServiceDeviceSettingses(Set serviceDeviceSettingses) {
        this.serviceDeviceSettingses = serviceDeviceSettingses;
    }
}


