package se.info24.pojo;
// Generated Jul 16, 2012 11:28:09 AM by Hibernate Tools 3.2.1.GA



/**
 * ServicesVisibleToGroupId generated by hbm2java
 */
public class ServicesVisibleToGroupId  implements java.io.Serializable {


     private String serviceId;
     private String groupId;

    public ServicesVisibleToGroupId() {
    }

    public ServicesVisibleToGroupId(String serviceId, String groupId) {
       this.serviceId = serviceId;
       this.groupId = groupId;
    }
   
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServicesVisibleToGroupId) ) return false;
		 ServicesVisibleToGroupId castOther = ( ServicesVisibleToGroupId ) other; 
         
		 return ( (this.getServiceId()==castOther.getServiceId()) || ( this.getServiceId()!=null && castOther.getServiceId()!=null && this.getServiceId().equals(castOther.getServiceId()) ) )
 && ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getServiceId() == null ? 0 : this.getServiceId().hashCode() );
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         return result;
   }   


}


