package se.info24.pojo;
// Generated Dec 11, 2013 10:32:58 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SupportCaseServiceLinks generated by hbm2java
 */
public class SupportCaseServiceLinks  implements java.io.Serializable {


     private SupportCaseServiceLinksId id;
     private Services services;
     private SupportCases supportCases;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;

    public SupportCaseServiceLinks() {
    }

	
    public SupportCaseServiceLinks(SupportCaseServiceLinksId id, Services services, SupportCases supportCases, String lastUpdatedByUserId) {
        this.id = id;
        this.services = services;
        this.supportCases = supportCases;
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public SupportCaseServiceLinks(SupportCaseServiceLinksId id, Services services, SupportCases supportCases, String lastUpdatedByUserId, Date createdDate, Date updatedDate) {
       this.id = id;
       this.services = services;
       this.supportCases = supportCases;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public SupportCaseServiceLinksId getId() {
        return this.id;
    }
    
    public void setId(SupportCaseServiceLinksId id) {
        this.id = id;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public SupportCases getSupportCases() {
        return this.supportCases;
    }
    
    public void setSupportCases(SupportCases supportCases) {
        this.supportCases = supportCases;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


