//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.30 at 11:07:48 AM IST 
//


package se.info24.reportsjaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductVariantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountSinceLastUpdate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CountTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}LastUpdatedByUserID"/>
 *         &lt;element ref="{}CreatedDate"/>
 *         &lt;element ref="{}UpdatedDate"/>
 *         &lt;element name="UpdatedDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objectID",
    "productVariantID",
    "countSinceLastUpdate",
    "countTotal",
    "lastUpdatedByUserID",
    "createdDate",
    "updatedDate",
    "updatedDateTCMV3"
})
@XmlRootElement(name = "ObjectProductVariantCounters")
public class ObjectProductVariantCounters {

    @XmlElement(name = "ObjectID", required = true)
    protected String objectID;
    @XmlElement(name = "ProductVariantID", required = true)
    protected String productVariantID;
    @XmlElement(name = "CountSinceLastUpdate")
    protected int countSinceLastUpdate;
    @XmlElement(name = "CountTotal")
    protected int countTotal;
    @XmlElement(name = "LastUpdatedByUserID", required = true)
    protected String lastUpdatedByUserID;
    @XmlElement(name = "CreatedDate", required = true)
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "UpdatedDate", required = true)
    protected String updatedDate;
    @XmlElement(name = "UpdatedDateTCMV3", required = true)
    protected String updatedDateTCMV3;

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectID(String value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the productVariantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductVariantID() {
        return productVariantID;
    }

    /**
     * Sets the value of the productVariantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductVariantID(String value) {
        this.productVariantID = value;
    }

    /**
     * Gets the value of the countSinceLastUpdate property.
     * 
     */
    public int getCountSinceLastUpdate() {
        return countSinceLastUpdate;
    }

    /**
     * Sets the value of the countSinceLastUpdate property.
     * 
     */
    public void setCountSinceLastUpdate(int value) {
        this.countSinceLastUpdate = value;
    }

    /**
     * Gets the value of the countTotal property.
     * 
     */
    public int getCountTotal() {
        return countTotal;
    }

    /**
     * Sets the value of the countTotal property.
     * 
     */
    public void setCountTotal(int value) {
        this.countTotal = value;
    }

    /**
     * Gets the value of the lastUpdatedByUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedByUserID() {
        return lastUpdatedByUserID;
    }

    /**
     * Sets the value of the lastUpdatedByUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedByUserID(String value) {
        this.lastUpdatedByUserID = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the updatedDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDateTCMV3() {
        return updatedDateTCMV3;
    }

    /**
     * Sets the value of the updatedDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDateTCMV3(String value) {
        this.updatedDateTCMV3 = value;
    }

}
