package se.info24.timPojo;
// Generated Dec 5, 2013 3:09:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private String pageId;
     private String pageTitle;
     private String pageNameOrUrl;
     private String pageHeaderThumbnailUrl;
     private String lastUpdatedByUserId;
     private Date createdDate;
     private Date updatedDate;
     private Set pageTranslationses = new HashSet(0);

    public Pages() {
    }

	
    public Pages(String pageId) {
        this.pageId = pageId;
    }
    public Pages(String pageId, String pageTitle, String pageNameOrUrl, String pageHeaderThumbnailUrl, String lastUpdatedByUserId, Date createdDate, Date updatedDate, Set pageTranslationses) {
       this.pageId = pageId;
       this.pageTitle = pageTitle;
       this.pageNameOrUrl = pageNameOrUrl;
       this.pageHeaderThumbnailUrl = pageHeaderThumbnailUrl;
       this.lastUpdatedByUserId = lastUpdatedByUserId;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.pageTranslationses = pageTranslationses;
    }
   
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getPageTitle() {
        return this.pageTitle;
    }
    
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }
    public String getPageNameOrUrl() {
        return this.pageNameOrUrl;
    }
    
    public void setPageNameOrUrl(String PageNameOrUrl) {
        this.pageNameOrUrl = PageNameOrUrl;
    }
    public String getPageHeaderThumbnailUrl() {
        return this.pageHeaderThumbnailUrl;
    }
    
    public void setPageHeaderThumbnailUrl(String pageHeaderThumbnailUrl) {
        this.pageHeaderThumbnailUrl = pageHeaderThumbnailUrl;
    }
    public String getLastUpdatedByUserId() {
        return this.lastUpdatedByUserId;
    }
    
    public void setLastUpdatedByUserId(String lastUpdatedByUserId) {
        this.lastUpdatedByUserId = lastUpdatedByUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Set getPageTranslationses() {
        return this.pageTranslationses;
    }
    
    public void setPageTranslationses(Set pageTranslationses) {
        this.pageTranslationses = pageTranslationses;
    }




}


