//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.12 at 01:04:12 PM IST 
//


package se.info24.devicejaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AddressID"/>
 *         &lt;element ref="{}AddressName"/>
 *         &lt;element ref="{}AddressDescription"/>
 *         &lt;element ref="{}AddressTypeID"/>
 *         &lt;element ref="{}AddressRegion"/>
 *         &lt;element ref="{}AddressStreet"/>
 *         &lt;element ref="{}AddressStreet2"/>
 *         &lt;element ref="{}AddressSuite"/>
 *         &lt;element ref="{}AddressZip"/>
 *         &lt;element ref="{}AddressCity"/>
 *         &lt;element ref="{}CountryID"/>
 *         &lt;element ref="{}CountryStateID"/>
 *         &lt;element ref="{}AddressPhone"/>
 *         &lt;element ref="{}AddressMobile"/>
 *         &lt;element ref="{}AddressFax"/>
 *         &lt;element ref="{}AddressEmail"/>
 *         &lt;element ref="{}AddressWeb"/>
 *         &lt;element ref="{}AddressIM"/>
 *         &lt;element ref="{}AddressLatitude"/>
 *         &lt;element ref="{}AddressLongitude"/>
 *         &lt;element ref="{}AddressDepth"/>
 *         &lt;element ref="{}LastUpdatedByUserID"/>
 *         &lt;element ref="{}CreatedDate"/>
 *         &lt;element ref="{}UpdatedDate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressID",
    "addressName",
    "addressDescription",
    "addressTypeID",
    "addressRegion",
    "addressStreet",
    "addressStreet2",
    "addressSuite",
    "addressZip",
    "addressCity",
    "countryID",
    "countryStateID",
    "addressPhone",
    "addressMobile",
    "addressFax",
    "addressEmail",
    "addressWeb",
    "addressIM",
    "addressLatitude",
    "addressLongitude",
    "addressDepth",
    "lastUpdatedByUserID",
    "createdDate",
    "updatedDate"
})
@XmlRootElement(name = "DeviceAddress")
public class DeviceAddress {

    @XmlElement(name = "AddressID", required = true)
    protected String addressID;
    @XmlElement(name = "AddressName", required = true)
    protected String addressName;
    @XmlElement(name = "AddressDescription", required = true)
    protected String addressDescription;
    @XmlElement(name = "AddressTypeID", required = true)
    protected AddressTypeID addressTypeID;
    @XmlElement(name = "AddressRegion", required = true)
    protected String addressRegion;
    @XmlElement(name = "AddressStreet", required = true)
    protected String addressStreet;
    @XmlElement(name = "AddressStreet2", required = true)
    protected String addressStreet2;
    @XmlElement(name = "AddressSuite", required = true)
    protected String addressSuite;
    @XmlElement(name = "AddressZip", required = true)
    protected String addressZip;
    @XmlElement(name = "AddressCity", required = true)
    protected String addressCity;
    @XmlElement(name = "CountryID", required = true)
    protected CountryID countryID;
    @XmlElement(name = "CountryStateID", required = true)
    protected String countryStateID;
    @XmlElement(name = "AddressPhone", required = true)
    protected String addressPhone;
    @XmlElement(name = "AddressMobile", required = true)
    protected String addressMobile;
    @XmlElement(name = "AddressFax", required = true)
    protected String addressFax;
    @XmlElement(name = "AddressEmail", required = true)
    protected String addressEmail;
    @XmlElement(name = "AddressWeb", required = true)
    protected String addressWeb;
    @XmlElement(name = "AddressIM", required = true)
    protected String addressIM;
    @XmlElement(name = "AddressLatitude", required = true)
    protected String addressLatitude;
    @XmlElement(name = "AddressLongitude", required = true)
    protected String addressLongitude;
    @XmlElement(name = "AddressDepth", required = true)
    protected String addressDepth;
    @XmlElement(name = "LastUpdatedByUserID", required = true)
    protected LastUpdatedByUserID lastUpdatedByUserID;
    @XmlElement(name = "CreatedDate", required = true)
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "UpdatedDate", required = true)
    protected XMLGregorianCalendar updatedDate;

    /**
     * Gets the value of the addressID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressID() {
        return addressID;
    }

    /**
     * Sets the value of the addressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressID(String value) {
        this.addressID = value;
    }

    /**
     * Gets the value of the addressName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * Sets the value of the addressName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressName(String value) {
        this.addressName = value;
    }

    /**
     * Gets the value of the addressDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressDescription() {
        return addressDescription;
    }

    /**
     * Sets the value of the addressDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressDescription(String value) {
        this.addressDescription = value;
    }

    /**
     * Gets the value of the addressTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link AddressTypeID }
     *     
     */
    public AddressTypeID getAddressTypeID() {
        return addressTypeID;
    }

    /**
     * Sets the value of the addressTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressTypeID }
     *     
     */
    public void setAddressTypeID(AddressTypeID value) {
        this.addressTypeID = value;
    }

    /**
     * Gets the value of the addressRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressRegion() {
        return addressRegion;
    }

    /**
     * Sets the value of the addressRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressRegion(String value) {
        this.addressRegion = value;
    }

    /**
     * Gets the value of the addressStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreet() {
        return addressStreet;
    }

    /**
     * Sets the value of the addressStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreet(String value) {
        this.addressStreet = value;
    }

    /**
     * Gets the value of the addressStreet2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreet2() {
        return addressStreet2;
    }

    /**
     * Sets the value of the addressStreet2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreet2(String value) {
        this.addressStreet2 = value;
    }

    /**
     * Gets the value of the addressSuite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressSuite() {
        return addressSuite;
    }

    /**
     * Sets the value of the addressSuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressSuite(String value) {
        this.addressSuite = value;
    }

    /**
     * Gets the value of the addressZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressZip() {
        return addressZip;
    }

    /**
     * Sets the value of the addressZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressZip(String value) {
        this.addressZip = value;
    }

    /**
     * Gets the value of the addressCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * Sets the value of the addressCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressCity(String value) {
        this.addressCity = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     * @return
     *     possible object is
     *     {@link CountryID }
     *     
     */
    public CountryID getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryID }
     *     
     */
    public void setCountryID(CountryID value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the countryStateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryStateID() {
        return countryStateID;
    }

    /**
     * Sets the value of the countryStateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryStateID(String value) {
        this.countryStateID = value;
    }

    /**
     * Gets the value of the addressPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPhone() {
        return addressPhone;
    }

    /**
     * Sets the value of the addressPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPhone(String value) {
        this.addressPhone = value;
    }

    /**
     * Gets the value of the addressMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressMobile() {
        return addressMobile;
    }

    /**
     * Sets the value of the addressMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressMobile(String value) {
        this.addressMobile = value;
    }

    /**
     * Gets the value of the addressFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressFax() {
        return addressFax;
    }

    /**
     * Sets the value of the addressFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressFax(String value) {
        this.addressFax = value;
    }

    /**
     * Gets the value of the addressEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressEmail() {
        return addressEmail;
    }

    /**
     * Sets the value of the addressEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressEmail(String value) {
        this.addressEmail = value;
    }

    /**
     * Gets the value of the addressWeb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressWeb() {
        return addressWeb;
    }

    /**
     * Sets the value of the addressWeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressWeb(String value) {
        this.addressWeb = value;
    }

    /**
     * Gets the value of the addressIM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressIM() {
        return addressIM;
    }

    /**
     * Sets the value of the addressIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressIM(String value) {
        this.addressIM = value;
    }

    /**
     * Gets the value of the addressLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLatitude() {
        return addressLatitude;
    }

    /**
     * Sets the value of the addressLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLatitude(String value) {
        this.addressLatitude = value;
    }

    /**
     * Gets the value of the addressLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLongitude() {
        return addressLongitude;
    }

    /**
     * Sets the value of the addressLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLongitude(String value) {
        this.addressLongitude = value;
    }

    /**
     * Gets the value of the addressDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressDepth() {
        return addressDepth;
    }

    /**
     * Sets the value of the addressDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressDepth(String value) {
        this.addressDepth = value;
    }

    /**
     * Gets the value of the lastUpdatedByUserID property.
     * 
     * @return
     *     possible object is
     *     {@link LastUpdatedByUserID }
     *     
     */
    public LastUpdatedByUserID getLastUpdatedByUserID() {
        return lastUpdatedByUserID;
    }

    /**
     * Sets the value of the lastUpdatedByUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastUpdatedByUserID }
     *     
     */
    public void setLastUpdatedByUserID(LastUpdatedByUserID value) {
        this.lastUpdatedByUserID = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

}
