//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 01:38:27 PM IST 
//


package se.info24.supportcasejaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SupportCaseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCaseSubject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImpactsGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByUserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByUserFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByUserLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedByPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCaseTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCasePriorityID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCaseImpactID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCaseStatusID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssignedToSupportOrganizationID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssignedToUserID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssignedToUserFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssignedToUserLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedDateForTIM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompletionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DueDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartDateTCMv3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompletionDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupportCaseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReproduceSteps" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResolutionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DurationEstimated" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DurationActual" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="IsUpdated" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SupportCaseNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="OptionalCountryID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{}GroupID"/>
 *         &lt;element name="IsSupportCaseTemplate" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="IsSupportCaseTimeReportPage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{}SupportCaseImpacts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportCaseTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportCasePriorities" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportCaseStatuses" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportCaseSubjectTemplates" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportCaseResolutionTemplates" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SupportOrganizations" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CostCenters" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SeqNo" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supportCaseID",
    "supportCaseSubject",
    "impactsGroupID",
    "reportedByUserID",
    "reportedByUserFirstName",
    "reportedByUserLastName",
    "reportedByUserName",
    "reportedByEmail",
    "reportedByPhone",
    "supportCaseTypeID",
    "supportCasePriorityID",
    "supportCaseImpactID",
    "supportCaseStatusID",
    "assignedToSupportOrganizationID",
    "assignedToUserID",
    "assignedToUserFirstName",
    "assignedToUserLastName",
    "reportedDate",
    "reportedDateForTIM",
    "dueDate",
    "startDate",
    "completionDate",
    "dueDateTCMV3",
    "startDateTCMv3",
    "completionDateTCMV3",
    "supportCaseDescription",
    "reproduceSteps",
    "resolutionText",
    "durationEstimated",
    "durationActual",
    "isUpdated",
    "supportCaseNumber",
    "deviceID",
    "deviceName",
    "deviceTypeID",
    "objectGroupName",
    "assetID",
    "countryID",
    "optionalCountryID",
    "groupID",
    "isSupportCaseTemplate",
    "isSupportCaseTimeReportPage",
    "supportCaseImpacts",
    "supportCaseTypes",
    "supportCasePriorities",
    "supportCaseStatuses",
    "supportCaseSubjectTemplates",
    "supportCaseResolutionTemplates",
    "supportOrganizations",
    "costCenters"
})
@XmlRootElement(name = "SupportCase")
public class SupportCase {

    @XmlElement(name = "SupportCaseID", required = true)
    protected String supportCaseID;
    @XmlElement(name = "SupportCaseSubject", required = true)
    protected String supportCaseSubject;
    @XmlElement(name = "ImpactsGroupID", required = true)
    protected String impactsGroupID;
    @XmlElement(name = "ReportedByUserID", required = true)
    protected String reportedByUserID;
    @XmlElement(name = "ReportedByUserFirstName", required = true)
    protected String reportedByUserFirstName;
    @XmlElement(name = "ReportedByUserLastName", required = true)
    protected String reportedByUserLastName;
    @XmlElement(name = "ReportedByUserName", required = true)
    protected String reportedByUserName;
    @XmlElement(name = "ReportedByEmail", required = true)
    protected String reportedByEmail;
    @XmlElement(name = "ReportedByPhone", required = true)
    protected String reportedByPhone;
    @XmlElement(name = "SupportCaseTypeID", required = true)
    protected String supportCaseTypeID;
    @XmlElement(name = "SupportCasePriorityID", required = true)
    protected String supportCasePriorityID;
    @XmlElement(name = "SupportCaseImpactID", required = true)
    protected String supportCaseImpactID;
    @XmlElement(name = "SupportCaseStatusID", required = true)
    protected String supportCaseStatusID;
    @XmlElement(name = "AssignedToSupportOrganizationID", required = true)
    protected String assignedToSupportOrganizationID;
    @XmlElement(name = "AssignedToUserID", required = true)
    protected String assignedToUserID;
    @XmlElement(name = "AssignedToUserFirstName", required = true)
    protected String assignedToUserFirstName;
    @XmlElement(name = "AssignedToUserLastName", required = true)
    protected String assignedToUserLastName;
    @XmlElement(name = "ReportedDate", required = true)
    protected String reportedDate;
    @XmlElement(name = "ReportedDateForTIM", required = true)
    protected String reportedDateForTIM;
    @XmlElement(name = "DueDate", required = true)
    protected String dueDate;
    @XmlElement(name = "StartDate", required = true)
    protected String startDate;
    @XmlElement(name = "CompletionDate", required = true)
    protected String completionDate;
    @XmlElement(name = "DueDateTCMV3", required = true)
    protected String dueDateTCMV3;
    @XmlElement(name = "StartDateTCMv3", required = true)
    protected String startDateTCMv3;
    @XmlElement(name = "CompletionDateTCMV3", required = true)
    protected String completionDateTCMV3;
    @XmlElement(name = "SupportCaseDescription", required = true)
    protected String supportCaseDescription;
    @XmlElement(name = "ReproduceSteps", required = true)
    protected String reproduceSteps;
    @XmlElement(name = "ResolutionText", required = true)
    protected String resolutionText;
    @XmlElement(name = "DurationEstimated", required = true)
    protected BigInteger durationEstimated;
    @XmlElement(name = "DurationActual", required = true)
    protected Integer durationActual;
    @XmlElement(name = "IsUpdated", required = true)
    protected BigInteger isUpdated;
    @XmlElement(name = "SupportCaseNumber")
    protected long supportCaseNumber;
    @XmlElement(name = "DeviceID", required = true)
    protected String deviceID;
    @XmlElement(name = "DeviceName", required = true)
    protected String deviceName;
    @XmlElement(name = "DeviceTypeID", required = true)
    protected String deviceTypeID;
    @XmlElement(name = "ObjectGroupName", required = true)
    protected String objectGroupName;
    @XmlElement(name = "AssetID", required = true)
    protected String assetID;
    @XmlElement(name = "CountryID", required = true)
    protected BigInteger countryID;
    @XmlElement(name = "OptionalCountryID", required = true)
    protected BigInteger optionalCountryID;
    @XmlElement(name = "GroupID", required = true)
    protected GroupID groupID;
    @XmlElement(name = "IsSupportCaseTemplate", required = true)
    protected BigInteger isSupportCaseTemplate;
    @XmlElement(name = "IsSupportCaseTimeReportPage")
    protected boolean isSupportCaseTimeReportPage;
    @XmlElement(name = "SupportCaseImpacts")
    protected List<SupportCaseImpacts> supportCaseImpacts;
    @XmlElement(name = "SupportCaseTypes")
    protected List<SupportCaseTypes> supportCaseTypes;
    @XmlElement(name = "SupportCasePriorities")
    protected List<SupportCasePriorities> supportCasePriorities;
    @XmlElement(name = "SupportCaseStatuses")
    protected List<SupportCaseStatuses> supportCaseStatuses;
    @XmlElement(name = "SupportCaseSubjectTemplates")
    protected List<SupportCaseSubjectTemplates> supportCaseSubjectTemplates;
    @XmlElement(name = "SupportCaseResolutionTemplates")
    protected List<SupportCaseResolutionTemplates> supportCaseResolutionTemplates;
    @XmlElement(name = "SupportOrganizations")
    protected List<SupportOrganizations> supportOrganizations;
    @XmlElement(name = "CostCenters")
    protected List<CostCenters> costCenters;
    @XmlAttribute(name = "SeqNo", required = true)
    protected int seqNo;

    /**
     * Gets the value of the supportCaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseID() {
        return supportCaseID;
    }

    /**
     * Sets the value of the supportCaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseID(String value) {
        this.supportCaseID = value;
    }

    /**
     * Gets the value of the supportCaseSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseSubject() {
        return supportCaseSubject;
    }

    /**
     * Sets the value of the supportCaseSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseSubject(String value) {
        this.supportCaseSubject = value;
    }

    /**
     * Gets the value of the impactsGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactsGroupID() {
        return impactsGroupID;
    }

    /**
     * Sets the value of the impactsGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactsGroupID(String value) {
        this.impactsGroupID = value;
    }

    /**
     * Gets the value of the reportedByUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByUserID() {
        return reportedByUserID;
    }

    /**
     * Sets the value of the reportedByUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByUserID(String value) {
        this.reportedByUserID = value;
    }

    /**
     * Gets the value of the reportedByUserFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByUserFirstName() {
        return reportedByUserFirstName;
    }

    /**
     * Sets the value of the reportedByUserFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByUserFirstName(String value) {
        this.reportedByUserFirstName = value;
    }

    /**
     * Gets the value of the reportedByUserLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByUserLastName() {
        return reportedByUserLastName;
    }

    /**
     * Sets the value of the reportedByUserLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByUserLastName(String value) {
        this.reportedByUserLastName = value;
    }

    /**
     * Gets the value of the reportedByUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByUserName() {
        return reportedByUserName;
    }

    /**
     * Sets the value of the reportedByUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByUserName(String value) {
        this.reportedByUserName = value;
    }

    /**
     * Gets the value of the reportedByEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByEmail() {
        return reportedByEmail;
    }

    /**
     * Sets the value of the reportedByEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByEmail(String value) {
        this.reportedByEmail = value;
    }

    /**
     * Gets the value of the reportedByPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedByPhone() {
        return reportedByPhone;
    }

    /**
     * Sets the value of the reportedByPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedByPhone(String value) {
        this.reportedByPhone = value;
    }

    /**
     * Gets the value of the supportCaseTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseTypeID() {
        return supportCaseTypeID;
    }

    /**
     * Sets the value of the supportCaseTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseTypeID(String value) {
        this.supportCaseTypeID = value;
    }

    /**
     * Gets the value of the supportCasePriorityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCasePriorityID() {
        return supportCasePriorityID;
    }

    /**
     * Sets the value of the supportCasePriorityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCasePriorityID(String value) {
        this.supportCasePriorityID = value;
    }

    /**
     * Gets the value of the supportCaseImpactID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseImpactID() {
        return supportCaseImpactID;
    }

    /**
     * Sets the value of the supportCaseImpactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseImpactID(String value) {
        this.supportCaseImpactID = value;
    }

    /**
     * Gets the value of the supportCaseStatusID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseStatusID() {
        return supportCaseStatusID;
    }

    /**
     * Sets the value of the supportCaseStatusID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseStatusID(String value) {
        this.supportCaseStatusID = value;
    }

    /**
     * Gets the value of the assignedToSupportOrganizationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedToSupportOrganizationID() {
        return assignedToSupportOrganizationID;
    }

    /**
     * Sets the value of the assignedToSupportOrganizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedToSupportOrganizationID(String value) {
        this.assignedToSupportOrganizationID = value;
    }

    /**
     * Gets the value of the assignedToUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedToUserID() {
        return assignedToUserID;
    }

    /**
     * Sets the value of the assignedToUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedToUserID(String value) {
        this.assignedToUserID = value;
    }

    /**
     * Gets the value of the assignedToUserFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedToUserFirstName() {
        return assignedToUserFirstName;
    }

    /**
     * Sets the value of the assignedToUserFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedToUserFirstName(String value) {
        this.assignedToUserFirstName = value;
    }

    /**
     * Gets the value of the assignedToUserLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedToUserLastName() {
        return assignedToUserLastName;
    }

    /**
     * Sets the value of the assignedToUserLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedToUserLastName(String value) {
        this.assignedToUserLastName = value;
    }

    /**
     * Gets the value of the reportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedDate() {
        return reportedDate;
    }

    /**
     * Sets the value of the reportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedDate(String value) {
        this.reportedDate = value;
    }

    /**
     * Gets the value of the reportedDateForTIM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedDateForTIM() {
        return reportedDateForTIM;
    }

    /**
     * Sets the value of the reportedDateForTIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedDateForTIM(String value) {
        this.reportedDateForTIM = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionDate(String value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the dueDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDateTCMV3() {
        return dueDateTCMV3;
    }

    /**
     * Sets the value of the dueDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDateTCMV3(String value) {
        this.dueDateTCMV3 = value;
    }

    /**
     * Gets the value of the startDateTCMv3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDateTCMv3() {
        return startDateTCMv3;
    }

    /**
     * Sets the value of the startDateTCMv3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDateTCMv3(String value) {
        this.startDateTCMv3 = value;
    }

    /**
     * Gets the value of the completionDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionDateTCMV3() {
        return completionDateTCMV3;
    }

    /**
     * Sets the value of the completionDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionDateTCMV3(String value) {
        this.completionDateTCMV3 = value;
    }

    /**
     * Gets the value of the supportCaseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportCaseDescription() {
        return supportCaseDescription;
    }

    /**
     * Sets the value of the supportCaseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportCaseDescription(String value) {
        this.supportCaseDescription = value;
    }

    /**
     * Gets the value of the reproduceSteps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReproduceSteps() {
        return reproduceSteps;
    }

    /**
     * Sets the value of the reproduceSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReproduceSteps(String value) {
        this.reproduceSteps = value;
    }

    /**
     * Gets the value of the resolutionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolutionText() {
        return resolutionText;
    }

    /**
     * Sets the value of the resolutionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolutionText(String value) {
        this.resolutionText = value;
    }

    /**
     * Gets the value of the durationEstimated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDurationEstimated() {
        return durationEstimated;
    }

    /**
     * Sets the value of the durationEstimated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDurationEstimated(BigInteger value) {
        this.durationEstimated = value;
    }

    /**
     * Gets the value of the durationActual property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getDurationActual() {
        return durationActual;
    }

    /**
     * Sets the value of the durationActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDurationActual(Integer value) {
        this.durationActual = value;
    }

    /**
     * Gets the value of the isUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsUpdated() {
        return isUpdated;
    }

    /**
     * Sets the value of the isUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsUpdated(BigInteger value) {
        this.isUpdated = value;
    }

    /**
     * Gets the value of the supportCaseNumber property.
     * 
     */
    public long getSupportCaseNumber() {
        return supportCaseNumber;
    }

    /**
     * Sets the value of the supportCaseNumber property.
     * 
     */
    public void setSupportCaseNumber(long value) {
        this.supportCaseNumber = value;
    }

    /**
     * Gets the value of the deviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

    /**
     * Gets the value of the deviceTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceTypeID() {
        return deviceTypeID;
    }

    /**
     * Sets the value of the deviceTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceTypeID(String value) {
        this.deviceTypeID = value;
    }

    /**
     * Gets the value of the objectGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectGroupName() {
        return objectGroupName;
    }

    /**
     * Sets the value of the objectGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectGroupName(String value) {
        this.objectGroupName = value;
    }

    /**
     * Gets the value of the assetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetID() {
        return assetID;
    }

    /**
     * Sets the value of the assetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetID(String value) {
        this.assetID = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCountryID(BigInteger value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the optionalCountryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOptionalCountryID() {
        return optionalCountryID;
    }

    /**
     * Sets the value of the optionalCountryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOptionalCountryID(BigInteger value) {
        this.optionalCountryID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link GroupID }
     *     
     */
    public GroupID getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupID }
     *     
     */
    public void setGroupID(GroupID value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the isSupportCaseTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsSupportCaseTemplate() {
        return isSupportCaseTemplate;
    }

    /**
     * Sets the value of the isSupportCaseTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsSupportCaseTemplate(BigInteger value) {
        this.isSupportCaseTemplate = value;
    }

    /**
     * Gets the value of the isSupportCaseTimeReportPage property.
     * 
     */
    public boolean isIsSupportCaseTimeReportPage() {
        return isSupportCaseTimeReportPage;
    }

    /**
     * Sets the value of the isSupportCaseTimeReportPage property.
     * 
     */
    public void setIsSupportCaseTimeReportPage(boolean value) {
        this.isSupportCaseTimeReportPage = value;
    }
 
    /**
     * Gets the value of the supportCaseImpacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseImpacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseImpacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCaseImpacts }
     * 
     * 
     */
    public List<SupportCaseImpacts> getSupportCaseImpacts() {
        if (supportCaseImpacts == null) {
            supportCaseImpacts = new ArrayList<SupportCaseImpacts>();
        }
        return this.supportCaseImpacts;
    }

    /**
     * Gets the value of the supportCaseTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCaseTypes }
     * 
     * 
     */
    public List<SupportCaseTypes> getSupportCaseTypes() {
        if (supportCaseTypes == null) {
            supportCaseTypes = new ArrayList<SupportCaseTypes>();
        }
        return this.supportCaseTypes;
    }

    /**
     * Gets the value of the supportCasePriorities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCasePriorities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCasePriorities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCasePriorities }
     * 
     * 
     */
    public List<SupportCasePriorities> getSupportCasePriorities() {
        if (supportCasePriorities == null) {
            supportCasePriorities = new ArrayList<SupportCasePriorities>();
        }
        return this.supportCasePriorities;
    }

    /**
     * Gets the value of the supportCaseStatuses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseStatuses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseStatuses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCaseStatuses }
     * 
     * 
     */
    public List<SupportCaseStatuses> getSupportCaseStatuses() {
        if (supportCaseStatuses == null) {
            supportCaseStatuses = new ArrayList<SupportCaseStatuses>();
        }
        return this.supportCaseStatuses;
    }

    /**
     * Gets the value of the supportCaseSubjectTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseSubjectTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseSubjectTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCaseSubjectTemplates }
     * 
     * 
     */
    public List<SupportCaseSubjectTemplates> getSupportCaseSubjectTemplates() {
        if (supportCaseSubjectTemplates == null) {
            supportCaseSubjectTemplates = new ArrayList<SupportCaseSubjectTemplates>();
        }
        return this.supportCaseSubjectTemplates;
    }

    /**
     * Gets the value of the supportCaseResolutionTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseResolutionTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseResolutionTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportCaseResolutionTemplates }
     * 
     * 
     */
    public List<SupportCaseResolutionTemplates> getSupportCaseResolutionTemplates() {
        if (supportCaseResolutionTemplates == null) {
            supportCaseResolutionTemplates = new ArrayList<SupportCaseResolutionTemplates>();
        }
        return this.supportCaseResolutionTemplates;
    }

    /**
     * Gets the value of the supportOrganizations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportOrganizations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportOrganizations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportOrganizations }
     * 
     * 
     */
    public List<SupportOrganizations> getSupportOrganizations() {
        if (supportOrganizations == null) {
            supportOrganizations = new ArrayList<SupportOrganizations>();
        }
        return this.supportOrganizations;
    }

    /**
     * Gets the value of the costCenters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costCenters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostCenters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostCenters }
     * 
     * 
     */
    public List<CostCenters> getCostCenters() {
        if (costCenters == null) {
            costCenters = new ArrayList<CostCenters>();
        }
        return this.costCenters;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     */
    public int getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     */
    public void setSeqNo(int value) {
        this.seqNo = value;
    }

}
