//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.07 at 11:33:12 AM IST 
//


package se.info24.supportcasejaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SupportCaseStatusID" maxOccurs="unbounded"/>
 *         &lt;element name="SortOrder" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ObjectCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IconURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SupportStatusTranslations" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SeqNo">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supportCaseStatusID",
    "sortOrder",
    "objectCode",
    "iconURL",
    "color",
    "supportStatusTranslations"
})
@XmlRootElement(name = "SupportCaseStatuses")
public class SupportCaseStatuses {

    @XmlElement(name = "SupportCaseStatusID", required = true)
    protected List<String> supportCaseStatusID;
    @XmlElement(name = "SortOrder")
    protected int sortOrder;
    @XmlElement(name = "ObjectCode", required = true)
    protected String objectCode;
    @XmlElement(name = "IconURL", required = true)
    protected String iconURL;
    @XmlElement(name = "Color", required = true)
    protected String color;
    @XmlElement(name = "SupportStatusTranslations")
    protected List<SupportStatusTranslations> supportStatusTranslations;
    @XmlAttribute(name = "SeqNo")
    protected Integer seqNo;

    /**
     * Gets the value of the supportCaseStatusID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportCaseStatusID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportCaseStatusID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupportCaseStatusID() {
        if (supportCaseStatusID == null) {
            supportCaseStatusID = new ArrayList<String>();
        }
        return this.supportCaseStatusID;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     */
    public int getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     */
    public void setSortOrder(int value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the objectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectCode() {
        return objectCode;
    }

    /**
     * Sets the value of the objectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectCode(String value) {
        this.objectCode = value;
    }

    /**
     * Gets the value of the iconURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconURL() {
        return iconURL;
    }

    /**
     * Sets the value of the iconURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconURL(String value) {
        this.iconURL = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the supportStatusTranslations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportStatusTranslations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportStatusTranslations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportStatusTranslations }
     * 
     * 
     */
    public List<SupportStatusTranslations> getSupportStatusTranslations() {
        if (supportStatusTranslations == null) {
            supportStatusTranslations = new ArrayList<SupportStatusTranslations>();
        }
        return this.supportStatusTranslations;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqNo(Integer value) {
        this.seqNo = value;
    }

}
