//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.29 at 03:44:12 PM IST 
//


package se.info24.commandsjaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.info24.tcmcommands package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MsgTimeStamp_QNAME = new QName("", "MsgTimeStamp");
    private final static QName _ResponseText_QNAME = new QName("", "ResponseText");
    private final static QName _MsgID_QNAME = new QName("", "MsgID");
    private final static QName _ResponseCode_QNAME = new QName("", "ResponseCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.info24.tcmcommands
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommandParameter }
     * 
     */
    public CommandParameter createCommandParameter() {
        return new CommandParameter();
    }

    /**
     * Create an instance of {@link TingcoCommands }
     * 
     */
    public TingcoCommands createTingcoCommands() {
        return new TingcoCommands();
    }

    /**
     * Create an instance of {@link Commands }
     * 
     */
    public Commands createCommands() {
        return new Commands();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link MsgStatus }
     * 
     */
    public MsgStatus createMsgStatus() {
        return new MsgStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgTimeStamp")
    public JAXBElement<XMLGregorianCalendar> createMsgTimeStamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MsgTimeStamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseText")
    public JAXBElement<String> createResponseText(String value) {
        return new JAXBElement<String>(_ResponseText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgID")
    public JAXBElement<String> createMsgID(String value) {
        return new JAXBElement<String>(_MsgID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseCode")
    public JAXBElement<Byte> createResponseCode(Byte value) {
        return new JAXBElement<Byte>(_ResponseCode_QNAME, Byte.class, null, value);
    }

}
