//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 12:00:02 PM IST 
//


package se.info24.groupsjaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MsgID"/>
 *         &lt;element ref="{}MsgTimeStamp"/>
 *         &lt;element ref="{}MsgStatus" minOccurs="0"/>
 *         &lt;element ref="{}Groups" minOccurs="0"/>
 *         &lt;element ref="{}EventTypess" minOccurs="0"/>
 *         &lt;element ref="{}DeliveryAccounts" minOccurs="0"/>
 *         &lt;element name="Exceeds200" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}FAQs" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TimeZone" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="UTC"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RegionalUnits" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Metric"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MsgVer" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CreateRef" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Info24"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgID",
    "msgTimeStamp",
    "msgStatus",
    "groups",
    "eventTypess",
    "deliveryAccounts",
    "exceeds200",
    "faQs"
})
@XmlRootElement(name = "tingcoGroups")
public class TingcoGroups {

    @XmlElement(name = "MsgID", required = true)
    protected String msgID;
    @XmlElement(name = "MsgTimeStamp", required = true)
    protected XMLGregorianCalendar msgTimeStamp;
    @XmlElement(name = "MsgStatus")
    protected MsgStatus msgStatus;
    @XmlElement(name = "Groups")
    protected Groups groups;
    @XmlElement(name = "EventTypess")
    protected EventTypess eventTypess;
    @XmlElement(name = "DeliveryAccounts")
    protected DeliveryAccounts deliveryAccounts;
    @XmlElement(name = "Exceeds200")
    protected int exceeds200;
    @XmlElement(name = "FAQs")
    protected FAQs faQs;
    @XmlAttribute(name = "TimeZone", required = true)
    protected String timeZone;
    @XmlAttribute(name = "RegionalUnits", required = true)
    protected String regionalUnits;
    @XmlAttribute(name = "MsgVer", required = true)
    protected BigDecimal msgVer;
    @XmlAttribute(name = "CreateRef", required = true)
    protected String createRef;

    /**
     * Gets the value of the msgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMsgTimeStamp() {
        return msgTimeStamp;
    }

    /**
     * Sets the value of the msgTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMsgTimeStamp(XMLGregorianCalendar value) {
        this.msgTimeStamp = value;
    }

    /**
     * Gets the value of the msgStatus property.
     * 
     * @return
     *     possible object is
     *     {@link MsgStatus }
     *     
     */
    public MsgStatus getMsgStatus() {
        return msgStatus;
    }

    /**
     * Sets the value of the msgStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgStatus }
     *     
     */
    public void setMsgStatus(MsgStatus value) {
        this.msgStatus = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link Groups }
     *     
     */
    public Groups getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Groups }
     *     
     */
    public void setGroups(Groups value) {
        this.groups = value;
    }

    /**
     * Gets the value of the eventTypess property.
     * 
     * @return
     *     possible object is
     *     {@link EventTypess }
     *     
     */
    public EventTypess getEventTypess() {
        return eventTypess;
    }

    /**
     * Sets the value of the eventTypess property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTypess }
     *     
     */
    public void setEventTypess(EventTypess value) {
        this.eventTypess = value;
    }

    /**
     * Gets the value of the deliveryAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryAccounts }
     *     
     */
    public DeliveryAccounts getDeliveryAccounts() {
        return deliveryAccounts;
    }

    /**
     * Sets the value of the deliveryAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryAccounts }
     *     
     */
    public void setDeliveryAccounts(DeliveryAccounts value) {
        this.deliveryAccounts = value;
    }

    /**
     * Gets the value of the exceeds200 property.
     * 
     */
    public int getExceeds200() {
        return exceeds200;
    }

    /**
     * Sets the value of the exceeds200 property.
     * 
     */
    public void setExceeds200(int value) {
        this.exceeds200 = value;
    }

    /**
     * Gets the value of the faQs property.
     * 
     * @return
     *     possible object is
     *     {@link FAQs }
     *     
     */
    public FAQs getFAQs() {
        return faQs;
    }

    /**
     * Sets the value of the faQs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FAQs }
     *     
     */
    public void setFAQs(FAQs value) {
        this.faQs = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the regionalUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionalUnits() {
        return regionalUnits;
    }

    /**
     * Sets the value of the regionalUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionalUnits(String value) {
        this.regionalUnits = value;
    }

    /**
     * Gets the value of the msgVer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMsgVer() {
        return msgVer;
    }

    /**
     * Sets the value of the msgVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMsgVer(BigDecimal value) {
        this.msgVer = value;
    }

    /**
     * Gets the value of the createRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateRef() {
        return createRef;
    }

    /**
     * Sets the value of the createRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateRef(String value) {
        this.createRef = value;
    }

}
