package se.info24.ismOperationsPojo;
// Generated Oct 9, 2013 2:36:52 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * ContainerFillings generated by hbm2java
 */
public class ContainerFillings  implements java.io.Serializable {


     private String dataItemId;
     private Date dataItemTime;
     private String containerId;
     private String groupId;
     private BigDecimal fillValue;
     private BigDecimal fillLevel;
     private String productVariantId;
     private String productVariantUnit;
     private BigDecimal productVariantDensity;
     private Short year;
     private Short month;
     private Short day;
     private Short hour;
     private Date createdDate;
     private Date updatedDate;

    public ContainerFillings() {
    }

	
    public ContainerFillings(String dataItemId, Date dataItemTime, String containerId, String groupId, BigDecimal fillValue, BigDecimal fillLevel) {
        this.dataItemId = dataItemId;
        this.dataItemTime = dataItemTime;
        this.containerId = containerId;
        this.groupId = groupId;
        this.fillValue = fillValue;
        this.fillLevel = fillLevel;
    }
    public ContainerFillings(String dataItemId, Date dataItemTime, String containerId, String groupId, BigDecimal fillValue, BigDecimal fillLevel, String productVariantId, String productVariantUnit, BigDecimal productVariantDensity, Short year, Short month, Short day, Short hour, Date createdDate, Date updatedDate) {
       this.dataItemId = dataItemId;
       this.dataItemTime = dataItemTime;
       this.containerId = containerId;
       this.groupId = groupId;
       this.fillValue = fillValue;
       this.fillLevel = fillLevel;
       this.productVariantId = productVariantId;
       this.productVariantUnit = productVariantUnit;
       this.productVariantDensity = productVariantDensity;
       this.year = year;
       this.month = month;
       this.day = day;
       this.hour = hour;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
    public String getDataItemId() {
        return this.dataItemId;
    }
    
    public void setDataItemId(String dataItemId) {
        this.dataItemId = dataItemId;
    }
    public Date getDataItemTime() {
        return this.dataItemTime;
    }
    
    public void setDataItemTime(Date dataItemTime) {
        this.dataItemTime = dataItemTime;
    }
    public String getContainerId() {
        return this.containerId;
    }
    
    public void setContainerId(String containerId) {
        this.containerId = containerId;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public BigDecimal getFillValue() {
        return this.fillValue;
    }
    
    public void setFillValue(BigDecimal fillValue) {
        this.fillValue = fillValue;
    }
    public BigDecimal getFillLevel() {
        return this.fillLevel;
    }
    
    public void setFillLevel(BigDecimal fillLevel) {
        this.fillLevel = fillLevel;
    }
    public String getProductVariantId() {
        return this.productVariantId;
    }
    
    public void setProductVariantId(String productVariantId) {
        this.productVariantId = productVariantId;
    }
    public String getProductVariantUnit() {
        return this.productVariantUnit;
    }
    
    public void setProductVariantUnit(String productVariantUnit) {
        this.productVariantUnit = productVariantUnit;
    }
    public BigDecimal getProductVariantDensity() {
        return this.productVariantDensity;
    }
    
    public void setProductVariantDensity(BigDecimal productVariantDensity) {
        this.productVariantDensity = productVariantDensity;
    }
    public Short getYear() {
        return this.year;
    }
    
    public void setYear(Short year) {
        this.year = year;
    }
    public Short getMonth() {
        return this.month;
    }
    
    public void setMonth(Short month) {
        this.month = month;
    }
    public Short getDay() {
        return this.day;
    }
    
    public void setDay(Short day) {
        this.day = day;
    }
    public Short getHour() {
        return this.hour;
    }
    
    public void setHour(Short hour) {
        this.hour = hour;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


