//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 01:46:10 PM IST 
//


package se.info24.appjaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgreementID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AgreementRoleTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActiveFromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ActiveToDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ActiveFromDateTCMv3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActiveToDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UpdatedDateTCMV3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsSupplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IsCustomer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LastUpdatedByUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="UpdatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element ref="{}AgreementRolesTypes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agreementID",
    "objectID",
    "objectName",
    "agreementRoleTypeId",
    "activeFromDate",
    "activeToDate",
    "activeFromDateTCMv3",
    "activeToDateTCMV3",
    "updatedDateTCMV3",
    "isSupplier",
    "isCustomer",
    "lastUpdatedByUser",
    "createdDate",
    "updatedDate",
    "agreementRolesTypes"
})
@XmlRootElement(name = "AgreementRoles")
public class AgreementRoles {

    @XmlElement(name = "AgreementID", required = true)
    protected String agreementID;
    @XmlElement(name = "ObjectID", required = true)
    protected String objectID;
    @XmlElement(name = "ObjectName", required = true)
    protected String objectName;
    @XmlElement(name = "AgreementRoleTypeId", required = true)
    protected String agreementRoleTypeId;
    @XmlElement(name = "ActiveFromDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activeFromDate;
    @XmlElement(name = "ActiveToDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activeToDate;
    @XmlElement(name = "ActiveFromDateTCMv3", required = true)
    protected String activeFromDateTCMv3;
    @XmlElement(name = "ActiveToDateTCMV3", required = true)
    protected String activeToDateTCMV3;
    @XmlElement(name = "UpdatedDateTCMV3", required = true)
    protected String updatedDateTCMV3;
    @XmlElement(name = "IsSupplier")
    protected int isSupplier;
    @XmlElement(name = "IsCustomer")
    protected int isCustomer;
    @XmlElement(name = "LastUpdatedByUser", required = true)
    protected String lastUpdatedByUser;
    @XmlElement(name = "CreatedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "UpdatedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDate;
    @XmlElement(name = "AgreementRolesTypes", required = true)
    protected AgreementRolesTypes agreementRolesTypes;

    /**
     * Gets the value of the agreementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementID() {
        return agreementID;
    }

    /**
     * Sets the value of the agreementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementID(String value) {
        this.agreementID = value;
    }

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectID(String value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the agreementRoleTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementRoleTypeId() {
        return agreementRoleTypeId;
    }

    /**
     * Sets the value of the agreementRoleTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementRoleTypeId(String value) {
        this.agreementRoleTypeId = value;
    }

    /**
     * Gets the value of the activeFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActiveFromDate() {
        return activeFromDate;
    }

    /**
     * Sets the value of the activeFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActiveFromDate(XMLGregorianCalendar value) {
        this.activeFromDate = value;
    }

    /**
     * Gets the value of the activeToDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActiveToDate() {
        return activeToDate;
    }

    /**
     * Sets the value of the activeToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActiveToDate(XMLGregorianCalendar value) {
        this.activeToDate = value;
    }

    /**
     * Gets the value of the activeFromDateTCMv3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFromDateTCMv3() {
        return activeFromDateTCMv3;
    }

    /**
     * Sets the value of the activeFromDateTCMv3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFromDateTCMv3(String value) {
        this.activeFromDateTCMv3 = value;
    }

    /**
     * Gets the value of the activeToDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveToDateTCMV3() {
        return activeToDateTCMV3;
    }

    /**
     * Sets the value of the activeToDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveToDateTCMV3(String value) {
        this.activeToDateTCMV3 = value;
    }

    /**
     * Gets the value of the updatedDateTCMV3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDateTCMV3() {
        return updatedDateTCMV3;
    }

    /**
     * Sets the value of the updatedDateTCMV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDateTCMV3(String value) {
        this.updatedDateTCMV3 = value;
    }

    /**
     * Gets the value of the isSupplier property.
     * 
     */
    public int getIsSupplier() {
        return isSupplier;
    }

    /**
     * Sets the value of the isSupplier property.
     * 
     */
    public void setIsSupplier(int value) {
        this.isSupplier = value;
    }

    /**
     * Gets the value of the isCustomer property.
     * 
     */
    public int getIsCustomer() {
        return isCustomer;
    }

    /**
     * Sets the value of the isCustomer property.
     * 
     */
    public void setIsCustomer(int value) {
        this.isCustomer = value;
    }

    /**
     * Gets the value of the lastUpdatedByUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedByUser() {
        return lastUpdatedByUser;
    }

    /**
     * Sets the value of the lastUpdatedByUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedByUser(String value) {
        this.lastUpdatedByUser = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDate(XMLGregorianCalendar value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the agreementRolesTypes property.
     * 
     * @return
     *     possible object is
     *     {@link AgreementRolesTypes }
     *     
     */
    public AgreementRolesTypes getAgreementRolesTypes() {
        return agreementRolesTypes;
    }

    /**
     * Sets the value of the agreementRolesTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgreementRolesTypes }
     *     
     */
    public void setAgreementRolesTypes(AgreementRolesTypes value) {
        this.agreementRolesTypes = value;
    }

}
